/*配置说明
* 1.不同查询模块均使用相同的index_config.html中的内容,改革文件名即可
* 2.html文件下方引用不同的search_config_模块名称.js
* 3.在search_config_模块名称.js中配置页面查询参数和展示参数
*/

var dictPath = portal +'/common/dict/';

var search_config_arr = ['TB_ST_ASJ','TB_ST_ASJXGRY'];


//查询条件配置
var search_config = {
    //查询接口地址
    url : compositQueryPath,
    basePath : basePath,
    export_url : basePath+'cetcQuery/exportExcel2003/zhcxXsaj',

    main_type : 'TB_ST_ASJ',//主表
    primary_key : 'ID',//主键

    query_title : '刑事案件',//页面标题名称
    sysType: 'xsaj',		//系统类型,用于区别查询模板的来源

    TB_ST_ASJ_type : 'TB_ST_ASJ',
    TB_ST_ASJ_title : '刑事案件基本信息',
    TB_ST_ASJ_init : ['ASJBH','AJMC','FXASJSJ','FXASJDD_DZMC','JYAQ'],    //默认显示的查询条件
    TB_ST_ASJ : [
        {field:'ASJBH',text:'案事件编号',input:'textbox',judge_dict:judge1},
        {field:'JJBH',text:'接警编号',input:'textbox',judge_dict:judge1},
        {field:'XCKYBH',text:'现场勘验编号',input:'textbox',judge_dict:judge1},
        {field:'ASJLYDM',text:'案事件来源代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_ASJLYFLDM.js',multiple:true},
        {field:'XSJQLBDM',text:'刑事警情类别代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_XSJQLBDM.js',multiple:true},
        {field:'ZCJDDM',text:'侦查阶段代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_XSAJBLZTDM.js',multiple:true},
        {field:'XSAJLASCJGDM',text:'刑事案件立案审查结果代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_XSAJLASCJGFLDM.js',multiple:true},
        {field:'AJLBDM',text:'案件类别代',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_XSJQLBDM.js',multiple:true},
        {field:'AJXLBDM',text:'案件小类别代码',input:'textbox',judge_dict:judge1},
        {field:'AJXLB_DMBCMS',text:'案件小类别代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'ZATZ_JYQK',text:'作案特征_简要情况',input:'textbox',judge_dict:judge1},
        {field:'TSSDDM',text:'特殊手段代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_TSSDDM.js',multiple:true},
        {field:'ZATZZDFL_JYQK',text:'作案特征自动分类_简要情况',input:'textbox',judge_dict:judge1},
        {field:'ZATZBCMS_JYQK',text:'作案特征补充描述_简要情况',input:'textbox',judge_dict:judge1},
        {field:'ZATZ_AJZATZJHBD',text:'作案特征_案件作案特征集合表达',input:'textbox',judge_dict:judge1},
        {field:'AJMC',text:'案件名称',input:'textbox',judge_dict:judge1},
        {field:'FXASJSJ',text:'发现案事件时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'FXASJDD_XZQHDM',text:'发现案事件地点行政区划代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GB_D_XZQHDM.js',multiple:true},
        {field:'AJLBDM',text:'案件类别代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_XSAJLBDM.js',multiple:true},
        {field:'FXASJDD_DZMC',text:'发现案事件地点_地址名称',input:'textbox',judge_dict:judge1},
        {field:'ASJFSSJ_ASJFSKSSJ',text:'案事件发生开始时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'ASJFSSJ_ASJFSJSSJ',text:'案事件发生结束时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'ASJFSSJ_RSDDM',text:'案事件发生时间日时段代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_RSDDM.js',multiple:true},
        {field:'ASJFSSJ_ZASJ_ZASJLBDM',text:'案事件发生时间作案时机类别代码',input:'textbox',judge_dict:judge1},
        {field:'ASJFSSJ_ZASJ_DMBCMS',text:'案事件发生时间作案时机代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'ASJFSDD_XZQHDM',text:'案事件发生地点行政区划代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GB_D_XZQHDM.js',multiple:true},
        {field:'ASJFSDD_DZMC',text:'案事件发生地点地址名称',input:'textbox',judge_dict:judge1},
        {field:'ASJFSDD_DQJD',text:'案事件发生地点经度',input:'textbox',judge_dict:judge1},
        {field:'ASJFSDD_DQWD',text:'案事件发生地点纬度',input:'textbox',judge_dict:judge1},
        {field:'ASJFSDD_DYLBDM',text:'案事件发生地点地域类别代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_DYLBDM.js',multiple:true},
        {field:'ASJFSDD_SACS_SACSLBDM',text:'案事件发生地点涉案场所类别代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_SACSFLDM.js',multiple:true},
        {field:'ASJFSDD_SACS_DMBCMS',text:'案事件发生地点涉案场所代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'ASJFSDD_KJBW_KJBWLBDM',text:'案事件发生地点空间部位类别代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_KJBWDM.js',multiple:true},
        {field:'ASJFSDD_KJBW_DMBCMS',text:'案事件发生地点空间部位代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'ASJFSDD_SFJZWN_PDBZ',text:'案事件发生地点是否建筑物内',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'BD_D_SFDM.js',multiple:true},
        {field:'ASJFSDD_JZWCS',text:'案事件发生地点建筑物层数',input:'textbox',judge_dict:judge1},
        {field:'ASJFSDD_ASJFSLC',text:'案事件发生地点案事件发生楼层',input:'textbox',judge_dict:judge1},
        {field:'ASJFSDD_SFZLZZ_PDBZ',text:'案事件发生地点是否租赁住宅',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'BD_D_SFDM.js',multiple:true},
        {field:'JYAQ',text:'简要案情',input:'textbox',judge_dict:judge1},
        {field:'SFSQ_PDBZ',text:'是否涉枪',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'BD_D_SFDM.js',multiple:true},
        {field:'SFSB_PDBZ',text:'是否涉爆',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'BD_D_SFDM.js',multiple:true},
        {field:'SFMA_PDBZ',text:'是否命案',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'BD_D_SFDM.js',multiple:true},
        {field:'SFSH_PDBZ',text:'是否涉黑',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'BD_D_SFDM.js',multiple:true},
        {field:'SFSJDQPCL_PDBZ',text:'是否涉及盗抢骗车辆BD_D_SFDM',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'BD_D_SFDM.js',multiple:true},
        {field:'SFSW_PDBZ',text:'是否涉外',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'BD_D_SFDM.js',multiple:true},
        {field:'SFGM_PDBZ',text:'是否拐卖',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'BD_D_SFDM.js',multiple:true},
        {field:'SWASJSWQK',text:'涉外案事件涉外情况',input:'textbox',judge_dict:judge1},
        {field:'ASJDBJBDM',text:'案事件督办级别代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_AJDBJBDM.js',multiple:true},
        {field:'LLFS_LLFSDM',text:'联络方式联络方式代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_LLFSDM.js',multiple:true},
        {field:'LLFS_DMBCMS',text:'联络方式代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'LLSJ',text:'联络时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'SY_JYQK',text:'事由_简要情况',input:'textbox',judge_dict:judge1},
        {field:'ZAZBSD_ZAZBSDDM',text:'作案准备手段代码GA_D_ZAZBSDDM',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_ZAZBSDDM.js',multiple:true},
        {field:'ZAZBSD_DMBCMS',text:'作案准备手段代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'JJSD_JJSDDM',text:'接近手段代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_JJSDDM.js',multiple:true},
        {field:'JJSD_DMBCMS',text:'接近手段_代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'MCMYSD_MCMYSDDM',text:'冒充冒用手段代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_MCMYSDDM.js',multiple:true},
        {field:'MCMYSD_DMBCMS',text:'冒充冒用手段代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'MCSF_MCSFDM',text:'冒充身份代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_ASJXGRYSFDM.js',multiple:true},
        {field:'MCSF_DMBCMS',text:'冒充身份代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'MCGXR_MCGXRDM',text:'冒充关系人代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_SHGXDM.js',multiple:true},
        {field:'MCGXR_DMBCMS',text:'冒充关系人代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'MYDWMY_MCDWMYDM',text:'"冒用单位名义代码"',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_ASJXGDWLBDM.js',multiple:true},
        {field:'MYDWMY_DMBCMS',text:'冒用单位名义代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'ZPSD_ZPSDDM',text:'诈骗手段代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_ZPSDDM.js',multiple:true},
        {field:'ZPSD_DMBCMS',text:'诈骗手段代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'XPSD_XPSDDM',text:'胁迫手段代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_XPSDFLDM.js',multiple:true},
        {field:'XPSD_DMBCMS',text:'胁迫手段代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'XPSYWP_SAWPDM',text:'胁迫使用物品涉案物品代码',input:'textbox',judge_dict:judge1},
        {field:'XPSYWP_DMBCMS',text:'胁迫使用物品代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'SBSD_SBSDDM',text:'施暴手段代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_SBSDFLDM.js',multiple:true},
        {field:'SBSD_DMBCMS',text:'施暴手段代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'JRJZKJFSJSD_JRJZKJFSJSDDM',text:'进入建筑空间方式及手段代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_JRJZKJFSJSDFLDM.js',multiple:true},
        {field:'JRJZKJFSJSD_DMBCMS',text:'进入建筑空间方式及手段代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'LKJZKJFS_LKJZKJFSDM',text:'离开建筑空间方式代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_LKJZKJFSFLDM.js',multiple:true},
        {field:'LKJZKJFS_DMBCMS',text:'离开建筑空间方式代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'JSSD_JSSDDM',text:'解锁手段代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_JSSDFLDM.js',multiple:true},
        {field:'JSSD_DMBCMS',text:'解锁手段代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'XTKJTPSD_XTKJTPSDDM',text:'箱体空间突破手段代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_XTKJTPSDDM.js',multiple:true},
        {field:'XTKJTPSD_DMBCMS',text:'箱体空间突破手段代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'XTKJTPSD_JSSD_JSSDDM',text:'解锁手段代码',input:'textbox',judge_dict:judge1},
        {field:'XTKJTPSD_JSSD_DMBCMS',text:'解锁手段代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'QQSD_QQSDDM',text:'窃取手段代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_QQSDFLDM.js',multiple:true},
        {field:'QQSD_DMBCMS',text:'窃取手段代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'YBSDDM',text:'引爆手段代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_YBSDDM.js',multiple:true},
        {field:'WLZASD_WLZASDDM',text:'网络作案手段代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_WLZASDDM.js',multiple:true},
        {field:'WLZASD_DMBCMS',text:'网络作案手段代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'XCWPFDCD_XCWPFDCDDM',text:'现场物品翻动程度代码',input:'textbox',judge_dict:judge1},
        {field:'XCWPFDCD_DMBCMS',text:'现场物品翻动程度代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'GRZCSD_GRZCSDDM',text:'干扰侦查手段代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_GRZCSDFLDM.js',multiple:true},
        {field:'GRZCSD_DMBCMS',text:'干扰侦查手段代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'FZXYRTSXW_FZXYRTSXWDM',text:'犯罪嫌疑人特殊行为代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_FZXYRTSXWDM.js',multiple:true},
        {field:'FZXYRTSXW_DMBCMS',text:'犯罪嫌疑人特殊行为代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'FZXYRSXZAHJQK',text:'犯罪嫌疑人熟悉作案环境情况',input:'textbox',judge_dict:judge1},
        {field:'QTSDTD_JYQK',text:'其他手段特点_简要情况',input:'textbox',judge_dict:judge1},
        {field:'ASJFSSJFX_ASJFSKSSJ',text:'案事件发生时间分析案事件发生开始时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'ASJFSSJFX_ASJFSJSSJ',text:'案事件发生时间分析案事件发生结束时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'ZARFX_RSXX',text:'作案人分析人数下限',input:'textbox',judge_dict:judge1},
        {field:'ZARFX_RSSX',text:'作案人分析人数上限',input:'textbox',judge_dict:judge1},
        {field:'FZXYRTZ_JYQK',text:'犯罪嫌疑人特征_简要情况',input:'textbox',judge_dict:judge1},
        {field:'FZXYRTSZC_FZXYRTSZCDM',text:'犯罪嫌疑人特殊专长代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_FZXYRTSZCDM.js',multiple:true},
        {field:'FZXYRTSZC_DMBCMS',text:'犯罪嫌疑人特殊专长代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'ZAGJ_SAWPDM',text:'作案工具_涉案物品代码',input:'textbox',judge_dict:judge1},
        {field:'ZAGJ_JYQK',text:'作案工具_简要情况',input:'textbox',judge_dict:judge1},
        {field:'ZADJMS',text:'作案动机描述',input:'textbox',judge_dict:judge1},
        {field:'ZAMDMS',text:'作案目的描述',input:'textbox',judge_dict:judge1},
        {field:'KJFWDM',text:'跨界范围代码',input:'textbox',judge_dict:judge1},
        {field:'LCZA_JYQK',text:'流窜作案_简要情况',input:'textbox',judge_dict:judge1},
        {field:'JHZA_JYQK',text:'结伙作案_简要情况',input:'textbox',judge_dict:judge1},
        {field:'GTFZFZXYRZHXSDM',text:'共同犯罪犯罪嫌疑人组合形式代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_GTFZFZXYRZHXSDM.js',multiple:true},
        {field:'GTFZFZXYRGC_GTFZFZXYRGCDM',text:'共同犯罪犯罪嫌疑人构成代码',input:'textbox',judge_dict:judge1},
        {field:'GTFZFZXYRGC_DMBCMS',text:'共同犯罪犯罪嫌疑人构成代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'XZWPFX_SAWP_SAWPDM',text:'选择物品分析_涉案物品_涉案物品代码',input:'textbox',judge_dict:judge1},
        {field:'XZWPFX_SAWP_DMBCMS',text:'选择物品分析_涉案物品_代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'SSWPQX_JYQK',text:'损失物品去向_简要情况',input:'textbox',judge_dict:judge1},
        {field:'FZXYRYLWP_JYQK',text:'犯罪嫌疑人遗留物品_简要情况',input:'textbox',judge_dict:judge1},
        {field:'XCKYWP_JYQK',text:'现场可疑物品_简要情况',input:'textbox',judge_dict:judge1},
        {field:'FXXS_JYQK',text:'发现线索_简要情况',input:'textbox',judge_dict:judge1},
        {field:'ASJSWRY_RS',text:'案事件死亡人员_人数',input:'textbox',judge_dict:judge1},
        {field:'ASJSSRY_RS',text:'案事件受伤人员_人数',input:'textbox',judge_dict:judge1},
        {field:'ASJSSCW_JYQK',text:'案事件损失财物_简要情况',input:'textbox',judge_dict:judge1},
        {field:'SSJZRMBY',text:'损失价值（人民币元）',input:'textbox',judge_dict:judge1},
        {field:'KYZSQZ_WPSL',text:'扣押制式枪支_物品数量',input:'textbox',judge_dict:judge1},
        {field:'KYMYQZ_WPSL',text:'扣押民用枪支_物品数量',input:'textbox',judge_dict:judge1},
        {field:'KYZZQZ_WPSL',text:'扣押自制枪支_物品数量',input:'textbox',judge_dict:judge1},
        {field:'KYFZQZ_WPSL',text:'扣押仿制枪支_物品数量',input:'textbox',judge_dict:judge1},
        {field:'KYQTQZ_WPSL',text:'扣押其他枪支_物品数量',input:'textbox',judge_dict:judge1},
        {field:'SLSJ',text:'受理时间',input:'textbox',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'SLDW_GAJGJGDM',text:'受理单位_公安机关机构代码',input:'textbox',judge_dict:judge1},
        {field:'SLDW_GAJGMC',text:'受理单位_公安机关名称',input:'textbox',judge_dict:judge1},
        {field:'LARQ',text:'立案日期',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'LADW_GAJGJGDM',text:'立案单位_公安机关机构代码',input:'textbox',judge_dict:judge1},
        {field:'LADW_GAJGMC',text:'立案单位_公安机关名称',input:'textbox',judge_dict:judge1},
        {field:'ZARY_RS',text:'作案人员_人数',input:'textbox',judge_dict:judge1},
        {field:'SJCWJZRMBY',text:'收缴财物价值（人民币元）',input:'textbox',judge_dict:judge1},
        {field:'ZCZJ_ZCXWYJMS',text:'侦查终结_侦查行为依据描述',input:'textbox',judge_dict:judge1},
        {field:'ZCZJ_ZXSJ01',text:'侦查终结_执行时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'ZCZJDW_GAJGJGDM',text:'侦查终结单位_公安机关机构代码',input:'textbox',judge_dict:judge1},
        {field:'ZCZJDW_GAJGMC',text:'侦查终结单位_公安机关名称',input:'textbox',judge_dict:judge1},
        {field:'YSSCQSRQ',text:'移送审查起诉日期',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'YSSCQSAJSCFHJDDM',text:'移送审查起诉案件审查返回决定代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_YSSCQSAJSCFHJDFLDM.js',multiple:true},
        {field:'SFCXAJ_PDBZ',text:'是否撤销案件_判断标识',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'BD_D_SFDM.js',multiple:true},
        {field:'CXAJYYDM',text:'撤销案件原因代码',input:'textbox',judge_dict:judge1},
        {field:'CXAJDW_GAJGJGDM',text:'撤销案件单位_公安机关机构代码',input:'textbox',judge_dict:judge1},
        {field:'CXAJDW_GAJGMC',text:'撤销案件单位_公安机关名称',input:'textbox',judge_dict:judge1},
        {field:'CXAJRQ',text:'撤销案件日期',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'XSAJXSGZJGDM',text:'刑事案件线索工作结果代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_XSAJXSGZJGDM.js',multiple:true},
        {field:'ZBR_XM',text:'主办人_姓名',input:'textbox',judge_dict:judge1},
        {field:'ZBR_GMSFHM',text:'主办人_公民身份号码',input:'textbox',judge_dict:judge1},
        {field:'ZBR_LXDH',text:'主办人_联系电话',input:'textbox',judge_dict:judge1},
        {field:'XBR_XM',text:'协办人_姓名',input:'textbox',judge_dict:judge1},
        {field:'XBR_GMSFHM',text:'协办人_公民身份号码',input:'textbox',judge_dict:judge1},
        {field:'XBR_LXDH',text:'协办人_联系电话',input:'textbox',judge_dict:judge1},
        {field:'XSJSFZR_XM',text:'刑事技术负责人_姓名',input:'textbox',judge_dict:judge1},
        {field:'XSJSFZR_GMSFHM',text:'刑事技术负责人_公民身份号码',input:'textbox',judge_dict:judge1},
        {field:'XSJSFZR_LXDH',text:'刑事技术负责人_联系电话',input:'textbox',judge_dict:judge1},
        {field:'GAJGFZR_XM',text:'公安机关负责人_姓名',input:'textbox',judge_dict:judge1},
        {field:'GAJGFZR_GMSFHM',text:'公安机关负责人_公民身份号码',input:'textbox',judge_dict:judge1},
        {field:'GAJGFZR_LXDH',text:'公安机关负责人_联系电话',input:'textbox',judge_dict:judge1},
        {field:'AJYWZTDM',text:'案件业务状态',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'BD_D_XSAJYWZTDM.js',multiple:true},
        {field:'PACJ_PDBZ',text:'破案采集_判断标识',input:'textbox',judge_dict:judge1},
        {field:'ZAXSDM',text:'作案形式代码',input:'textbox',judge_dict:judge1},
        {field:'PAFSDM',text:'破案方式代码',input:'textbox',judge_dict:judge1},
        {field:'PASJ',text:'破案时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'GXBMDM',text:'管辖部门代码',input:'textbox',judge_dict:judge1},
        {field:'GXPCSDM',text:'所属派出所代码',input:'textbox',judge_dict:judge1},
        {field:'GXFXJDM',text:'所属分县局代码',input:'textbox',judge_dict:judge1},
        {field:'GXSJDM',text:'所属市局代码',input:'textbox',judge_dict:judge1},
        {field:'BADW_GAJGMC',text:'办案单位_公安机关名称',input:'textbox',judge_dict:judge1},
        {field:'BADW_GAJGJGDM',text:'办案单位_公安机关机构代码',input:'textbox',judge_dict:judge1},
        {field:'SFKYSC_PDBS',text:'是否可以删除标识',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'BD_D_SFDM.js',multiple:true},
        {field:'GAJGDWFLDM',text:'单位分类代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_DWFLDM.js',multiple:true},
        {field:'XT_LRSJ',text:'录入时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'XT_LRRXM',text:'录入人姓名',input:'textbox',judge_dict:judge1},
        {field:'XT_LRRID',text:'录入人ID',input:'textbox',judge_dict:judge1},
        {field:'XT_LRRBM',text:'录入人部门',input:'textbox',judge_dict:judge1},
        {field:'XT_LRRBMID',text:'录入人部门ID',input:'textbox',judge_dict:judge1},
        {field:'XT_LRIP',text:'录入IP',input:'textbox',judge_dict:judge1},
        {field:'XT_ZHXGSJ',text:'最后修改时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'XT_ZHXGRXM',text:'最后修改人姓名',input:'textbox',judge_dict:judge1},
        {field:'XT_ZHXGRID',text:'最后修改人ID',input:'textbox',judge_dict:judge1},
        {field:'XT_ZHXGRBM',text:'最后修改人部门',input:'textbox',judge_dict:judge1},
        {field:'XT_ZHXGRBMID',text:'最后修改人部门ID',input:'textbox',judge_dict:judge1},
        {field:'XT_ZHXGIP',text:'最后修改IP',input:'textbox',judge_dict:judge1},
        {field:'XT_ZXBZ',text:'注销标志',input:'textbox',judge_dict:judge1},
        {field:'XT_ZXYY',text:'注销原因',input:'textbox',judge_dict:judge1},
        {field:'XT_ZXYYBZ',text:'注销原因备注',input:'textbox',judge_dict:judge1},
        {field:'OLD_SYSTEMID',text:'老警综主键',input:'textbox',judge_dict:judge1},
        {field:'YSQSRQ',text:'移送起诉日期',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'YSQS_GAJGJGDM',text:'移送起诉_公安机关机构代码',input:'textbox',judge_dict:judge1},
        {field:'YSQS_GAJGMC',text:'移送起诉_公安机关名称',input:'textbox',judge_dict:judge1},
        {field:'FXASJDD_DZID',text:'发现案事件地点_地址ID',input:'textbox',judge_dict:judge1},
        {field:'ASJFSDD_DZID',text:'案事件发生地点_地址ID',input:'textbox',judge_dict:judge1},
        {field:'AJYWZTMXDM',text:'案件业务状态明细代码',input:'textbox',judge_dict:judge1},
        {field:'BJSJ',text:'报警时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'AJXZDM',text:'案件性质代码',input:'textbox',judge_dict:judge1},
        {field:'AJXZMC',text:'案件性质名称',input:'textbox',judge_dict:judge1},
        {field:'ASJFSDD_SFBZ',text:'案事件发生地点是否标准',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'BD_D_SFDM.js',multiple:true},
        {field:'SFZA',text:'是否转案',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'BD_D_SFDM.js',multiple:true},



    ],
    TB_ST_ASJXGRY_type : 'TB_ST_ASJXGRY',
    TB_ST_ASJXGRY_title : '案事件相关人员',
    TB_ST_ASJXGRY_init : [],    //默认显示的查询条件
    TB_ST_ASJXGRY : [
        {field:'XXZJBH',text:'信息主键编号',input:'textbox',judge_dict:judge1},
        {field:'ASJBH',text:'案事件编号',input:'textbox',judge_dict:judge1},
        {field:'ASJXGRYBH',text:'案事件相关人员编号',input:'textbox',judge_dict:judge1},
        {field:'ASJXGRYJSDM',text:'案事件相关人员角色代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_ASJXGRYJSDM.js',multiple:true},
        {field:'ASJZCXWLBDM',text:'侦查行为代码',input:'textbox',judge_dict:judge1},
        {field:'RSQFJGDM',text:'人身侵犯结果代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_RSQFJGDM.js',multiple:true},
        {field:'RSSHCDDM',text:'人身伤害程度代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GA_D_RSSHCDDM.js',multiple:true},
        {field:'BMCH',text:'别名绰号',input:'textbox',judge_dict:judge1},
        {field:'YWXM',text:'英文姓名',input:'textbox',judge_dict:judge1},
        {field:'TSSFDM',text:'特殊身份',input:'textbox',judge_dict:judge1},
        {field:'CYZJ_CYZJDM',text:'常用证件_常用证件代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'KX_D_CYZJDM.js',multiple:true},
        {field:'CYZJ_DMBCMS',text:'常用证件_代码补充描述',input:'textbox',judge_dict:judge1},
        {field:'CYZJ_ZJHM',text:'常用证件_证件号码',input:'textbox',judge_dict:judge1},
        {field:'XM',text:'姓名',input:'textbox',judge_dict:judge1},
        {field:'CYM',text:'曾用名',input:'textbox',judge_dict:judge1},
        {field:'CSRQ',text:'出生日期',input:'textbox',judge_dict:judge1},
        {field:'XBDM',text:'性别代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GB_D_XBDM.js',multiple:true},
        {field:'GJDM',text:'国籍代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GB_D_GJHDQDM.js',multiple:true},
        {field:'JGDM',text:'籍贯省市县代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GB_D_XZQHDM.js',multiple:true},
        {field:'MZDM',text:'民族代码GB_D_MZDM',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GB_D_MZDM.js',multiple:true},
        {field:'WHCDDM',text:'文化程度代码',input:'textbox',judge_dict:judge1},
        {field:'HYZKDM',text:'婚姻状况代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GB_D_HYZKDM.js',multiple:true},
        {field:'ZYLBDM',text:'职业类别代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'KX_D_ZYLBDM.js',multiple:true},
        {field:'XZZ_DZID',text:'现住址_地址ID',input:'textbox',judge_dict:judge1},
        {field:'XZZ_JD',text:'现住址_经度',input:'textbox',judge_dict:judge1},
        {field:'XZZ_WD',text:'现住址_纬度',input:'textbox',judge_dict:judge1},
        {field:'XZZ_XZQHDM',text:'现住址_行政区划代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GB_D_XZQHDM.js',multiple:true},
        {field:'XZZ_DZMC',text:'现住址_地址名称',input:'textbox',judge_dict:judge1},
        {field:'BAR_GZDW',text:'工作单位',input:'textbox',judge_dict:judge1},
        {field:'HJDZ_XZQHDM',text:'户籍地址_行政区划代码',input:'combobox',
            judge_dict: judge3,condition_dict:dictPath+'GB_D_XZQHDM.js',multiple:true},
        {field:'HJDZ_DZMC',text:'户籍地址_地址名称',input:'textbox',judge_dict:judge1},
        {field:'BAR_LXDH',text:'联系电话',input:'textbox',judge_dict:judge1},
        {field:'WSFZYY',text:'无身份证原因',input:'textbox',judge_dict:judge1},
        {field:'BAR_BZ',text:'备注',input:'textbox',judge_dict:judge1},
        {field:'GXPCSDM',text:'所属派出所代码',input:'textbox',judge_dict:judge1},
        {field:'GXFXJDM',text:'所属分县局代码',input:'textbox',judge_dict:judge1},
        {field:'GXSJDM',text:'所属市局代码',input:'textbox',judge_dict:judge1},
        {field:'XT_LRSJ',text:'录入时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'XT_LRRXM',text:'录入人姓名',input:'textbox',judge_dict:judge1},
        {field:'XT_LRRID',text:'录入人ID',input:'textbox',judge_dict:judge1},
        {field:'XT_LRRBM',text:'录入人部门',input:'textbox',judge_dict:judge1},
        {field:'XT_LRRBMID',text:'录入人部门ID',input:'textbox',judge_dict:judge1},
        {field:'XT_LRIP',text:'录入IP',input:'textbox',judge_dict:judge1},
        {field:'XT_ZHXGSJ',text:'最后修改时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'XT_ZHXGRXM',text:'最后修改人姓名',input:'textbox',judge_dict:judge1},
        {field:'XT_ZHXGRID',text:'最后修改人ID',input:'textbox',judge_dict:judge1},
        {field:'XT_ZHXGRBM',text:'最后修改人部门',input:'textbox',judge_dict:judge1},
        {field:'XT_ZHXGRBMID',text:'最后修改人部门ID',input:'textbox',judge_dict:judge1},
        {field:'XT_ZHXGIP',text:'最后修改IP',input:'textbox',judge_dict:judge1},
        {field:'XT_ZXBZ',text:'注销标志',input:'textbox',judge_dict:judge1},
        {field:'XT_ZXYY',text:'注销原因',input:'textbox',judge_dict:judge1},
        {field:'XT_ZXYYBZ',text:'注销原因备注',input:'textbox',judge_dict:judge1},
        {field:'RYID',text:'人员ID',input:'textbox',judge_dict:judge1},
        {field:'OLD_RYBH',text:'老警综人员编号',input:'textbox',judge_dict:judge1},
        {field:'OLD_RKID',text:'老警综实有人口ID',input:'textbox',judge_dict:judge1},
        {field:'OLD_AJBH',text:'老警综案件编号',input:'textbox',judge_dict:judge1},
        {field:'OLD_SYSTEMID',text:'老警综主键',input:'textbox',judge_dict:judge1},
        {field:'HJDZ_DZID',text:'户籍地址ID',input:'textbox',judge_dict:judge1},
        {field:'SYDWID',text:'实有单位ID',input:'textbox',judge_dict:judge1},
    
    ]
};


