/*配置说明
* 1.不同查询模块均使用相同的index_config.html中的内容,改革文件名即可
* 2.html文件下方引用不同的search_config_模块名称.js
* 3.在search_config_模块名称.js中配置页面查询参数和展示参数
*/

var dictPath = portal +'/common/dict/';

var search_config_arr = ['TB_ST_JQ','TB_JQ_XYR'];


//查询条件配置
var search_config = {
    //查询接口地址
    url : compositQueryPath,
    basePath : basePath,
    export_url : basePath+'cetcQuery/exportExcel2003/zhcxJcj',

    main_type : 'TB_ST_JQ',//主表
    primary_key : 'ID',//主键

    query_title : '接处警',//页面标题名称
    sysType: 'jcj',		//系统类型,用于区别查询模板的来源
    
    TB_ST_JQ_type : 'TB_ST_JQ',
    TB_ST_JQ_title : '警情信息',
    TB_ST_JQ_init : ['JQBH','ASJBH','CLJQR_XM','CJDW_GAJGMC','BAR_LXDH','SPR_XM'],    //默认显示的查询条件
    TB_ST_JQ : [
        {field:'XXZJBH',text:'信息主键编号',input:'textbox',judge_dict: judge1},
        {field:'JQBH',text:'警情编号',input:'textbox',judge_dict: judge1},
        {field:'ASJBH',text:'案事件编号',input:'textbox',judge_dict: judge1},
        {field:'JJDBH',text:'接警单编号',input:'textbox',judge_dict: judge1},
        {field:'XCKYBH',text:'现场勘验编号',input:'textbox',judge_dict: judge1},
        {field:'JQLYDM',text:'警情来源代码',input:'combobox',judge_dict: judge3,condition_dict:dictPath+'BD_D_JQLYDM.js',multiple:true},
        {field:'BJFSDM',text:'报警方式代码',input:'combobox',judge_dict: judge3,condition_dict:dictPath+'BD_D_BJFSDM.js',multiple:true},
        {field:'BJSJ_RQSJ',text:'报警时间_日期时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'FSSJ',text:'发现时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'JDZLSJ',text:'接到指令时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'JQFSSJ_JQFSKSSJ',text:'警情发生时间_警情发生开始时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'JQFSSJ_JQFSJSSJ',text:'警情发生时间_警情发生开始时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'SFDZ_DZMC',text:'事发地址_地址名称',input:'textbox',judge_dict: judge1},
        {field:'SFBZDZ_DZID',text:'事发标准地址_地址ID',input:'textbox',judge_dict: judge1},
        {field:'SFBZDZ_XZQHDM',text:'事发标准地点_行政区划代码',input:'textbox',judge_dict: judge1},
        {field:'SFBZDZ_DZMC',text:'事发标准地点_地址名称',input:'textbox',judge_dict: judge1},
        {field:'SFBZDZ_DQJD',text:'事发标准地址_经度',input:'textbox',judge_dict: judge1},
        {field:'SFBZDZ_DQWD',text:'事发标准地址_纬度',input:'textbox',judge_dict: judge1},
        {field:'JQLBDM',text:'警情类别代码',input:'combobox',judge_dict: judge3,condition_dict:dictPath+'BD_D_JQLBDM.js',multiple:true},
        {field:'ZHZXXTJQMS',text:'指挥中心系统警情描述',input:'textbox',judge_dict: judge1},
        {field:'JYAQ',text:'简要警情',input:'textbox',judge_dict: judge1},
        {field:'DDXCSJ',text:'到达现场时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'CLJQR_JMSFHM',text:'处警人_居民身份号码',input:'textbox',judge_dict: judge1},
        {field:'CLJQR_XM',text:'处警人_姓名',input:'textbox',judge_dict: judge1},
        {field:'CJJSSJ',text:'处警结束时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'CJCLJG',text:'处警处理结果',input:'combobox',judge_dict: judge3,condition_dict:dictPath+'BD_D_JQCLJGDM.js',multiple:true},
        {field:'CJCLYJ',text:'处理意见',input:'textbox',judge_dict: judge1},
        {field:'CJDW_GAJGMC',text:'处警单位_公安机关名称',input:'textbox',judge_dict: judge1},
        {field:'CJDW_GAJGJGDM',text:'处警单位_公安机关机构代码',input:'textbox',judge_dict: judge1},
        {field:'CJR_JMSFHM',text:'出警人_居民身份号码',input:'textbox',judge_dict: judge1},
        {field:'CJR_XM',text:'出警人_姓名',input:'textbox',judge_dict: judge1},
        {field:'CDJLRS',text:'出动警力（人数）',input:'textbox',judge_dict: judge1},
        {field:'CDCZ',text:'出动船只',input:'textbox',judge_dict: judge1},
        {field:'CDHKQ',text:'出动航空器',input:'textbox',judge_dict: judge1},
        {field:'CDJDCL',text:'出动机动车（辆）',input:'textbox',judge_dict: judge1},
        {field:'BAR_XM',text:'报案人_姓名',input:'textbox',judge_dict: judge1},
        {field:'BAR_XBDM',text:'报案人_性别代码',input:'textbox',judge_dict: judge1},
        {field:'BAR_XBDM_DICTMC',text:'报案人_性别名称',input:'textbox',judge_dict: judge1},
        {field:'BAR_LXDH',text:'报案人_ 联系电话',input:'textbox',judge_dict: judge1},
        {field:'BAR_NL',text:'报案人_年龄',input:'textbox',judge_dict: judge1},
        {field:'BAR_XZZ_DZMC',text:'报案人_现住址_地址名称',input:'textbox',judge_dict: judge1},
        {field:'BAR_CYZJ_ZJHM',text:'报案人_身份证件号码',input:'textbox',judge_dict: judge1},
        {field:'ZHZXJJR_XM',text:'指挥中心接警员_姓名',input:'textbox',judge_dict: judge1},
        {field:'JJR_XM',text:'接警人_姓名',input:'textbox',judge_dict: judge1},
        {field:'JJDW_GAJGMC',text:'接警单位_公安机关名称',input:'textbox',judge_dict: judge1},
        {field:'JJDW_GAJGJGDM',text:'接警单位_公安机关机构代码',input:'textbox',judge_dict: judge1},
        {field:'ZHRS',text:'抓获人数',input:'textbox',judge_dict: judge1},
        {field:'JJQZRS',text:'解救群众人数',input:'textbox',judge_dict: judge1},
        {field:'JZSYRS',text:'救助伤员人数',input:'textbox',judge_dict: judge1},
        {field:'JJBGMFNRS',text:'解救被拐卖妇女人数',input:'textbox',judge_dict: judge1},
        {field:'JJBGMETRS',text:'解救被拐卖儿童人数',input:'textbox',judge_dict: judge1},
        {field:'JJPWRS',text:'继续盘问人数',input:'textbox',judge_dict: judge1},
        {field:'TFRS',text:'逃犯人数',input:'textbox',judge_dict: judge1},
        {field:'ASJSWRY_RS',text:'案事件死亡人员_人数',input:'textbox',judge_dict: judge1},
        {field:'ASJSSRY_RS',text:'案事件受伤人员_人数',input:'textbox',judge_dict: judge1},
        {field:'ASJSSJZRMBY',text:'案事件损失价值（人民币元）',input:'textbox',judge_dict: judge1},
        {field:'SAZZ',text:'涉案总值',input:'textbox',judge_dict: judge1},
        {field:'JQZTDM',text:'警情状态代码',input:'combobox',judge_dict: judge3,condition_dict:dictPath+'BD_D_JQZTDM.js',multiple:true},
        {field:'DTBZ_PDBS',text:'地图标注状态',input:'textbox',judge_dict: judge1},
        {field:'QQXKXT_PDBS',text:'请求现勘系统状态',input:'textbox',judge_dict: judge1},
        {field:'SJZJMC',text:'收集证据名称',input:'textbox',judge_dict: judge1},
        {field:'SJZJJS',text:'收集证据件数',input:'textbox',judge_dict: judge1},
        {field:'ZZCLMC',text:'制作材料名称',input:'textbox',judge_dict: judge1},
        {field:'ZZCLFS',text:'制作材料份数',input:'textbox',judge_dict: judge1},
        {field:'SPR_XM',text:'审批人_姓名',input:'textbox',judge_dict: judge1},
        {field:'SPSJ',text:'审批时间',input:'textbox',judge_dict: judge1},
        {field:'SPCLJG',text:'审批处理结果',input:'combobox',judge_dict: judge3,condition_dict:dictPath+'BD_D_SPJG.js',multiple:true},
        {field:'SPYJ',text:'审批意见',input:'textbox',judge_dict: judge1},
        {field:'SPZT',text:'审批状态',input:'combobox',judge_dict: judge3,condition_dict:dictPath+'BD_D_CQZTDM.js',multiple:true},
        {field:'JZJQ_CZZXSJ',text:'经侦警情_处置执行时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'JZJQ_JBYJ',text:'经侦警情_审批交办意见',input:'textbox',judge_dict: judge1},
        {field:'JZJQ_PDBS',text:'经侦警情_判断标识',input:'textbox',judge_dict: judge1},
        {field:'ZHZXJQ_PDBS',text:'指挥中心警情_判断标识',input:'textbox',judge_dict: judge1},
        {field:'YSSJ',text:'移送时间',input:'textbox',judge_dict: judge1},
        {field:'YSYY',text:'移送原因',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'YSDW_GAJGMC',text:'移送单位_公安机关名称',input:'textbox',judge_dict: judge1},
        {field:'YSDW_GAJGJGDM',text:'移送单位_公安机关机构代码',input:'textbox',judge_dict: judge1},
        {field:'YSR_XM',text:'移送人_姓名',input:'textbox',judge_dict: judge1},
        {field:'YSR_SFZH',text:'移送人_身份证号',input:'textbox',judge_dict: judge1},
        {field:'YSR_LXDH',text:'移送人_联系电话',input:'textbox',judge_dict: judge1},
        {field:'YSJQJSDW_GAJGMC',text:'移送警情接收单位_公安机关名称',input:'textbox',judge_dict: judge1},
        {field:'YSJQJSDW_GAJGJGDM',text:'移送警情接收单位_公安机关机构代码',input:'textbox',judge_dict: judge1},
        {field:'GXPCSDM',text:'所属派出所代码',input:'textbox',judge_dict: judge1},
        {field:'GXFXJDM',text:'所属分县局代码',input:'textbox',judge_dict: judge1},
        {field:'GXSJDM',text:'所属市局代码',input:'textbox',judge_dict: judge1},
        {field:'JJZ_SYSJX',text:'老警综剩余数据项',input:'textbox',judge_dict: judge1},
        {field:'XT_LRSJ',text:'录入时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'XT_LRRXM',text:'录入人姓名',input:'textbox',judge_dict: judge1},
        {field:'XT_LRRID',text:'录入人ID',input:'textbox',judge_dict: judge1},
        {field:'XT_LRRBM',text:'录入人部门',input:'textbox',judge_dict: judge1},
        {field:'XT_LRRBMID',text:'录入人部门ID',input:'textbox',judge_dict: judge1},
        {field:'XT_LRIP',text:'录入IP',input:'textbox',judge_dict: judge1},
        {field:'XT_ZHXGSJ',text:'最后修改时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'XT_ZHXGRXM',text:'最后修改人姓名',input:'textbox',judge_dict: judge1},
        {field:'XT_ZHXGRID',text:'最后修改人ID',input:'textbox',judge_dict: judge1},
        {field:'XT_ZHXGRBM',text:'最后修改人部门',input:'textbox',judge_dict: judge1},
        {field:'XT_ZHXGRBMID',text:'最后修改人部门ID',input:'textbox',judge_dict: judge1},
        {field:'XT_ZHXGIP',text:'最后修改IP',input:'textbox',judge_dict: judge1},
        {field:'XT_ZXBZ',text:'注销标志',input:'textbox',judge_dict: judge1},
        {field:'XT_ZXYY',text:'注销原因',input:'textbox',judge_dict: judge1},
        {field:'XT_ZXYYBZ',text:'注销原因备注',input:'textbox',judge_dict: judge1},
        {field:'OLD_SYSTEMID',text:'老警综主键',input:'textbox',judge_dict: judge1},
        {field:'OLD_DZID',text:'老警综地址ID',input:'textbox',judge_dict: judge1},
        {field:'JQLYFSDM',text:'警情来源方式',input:'combobox',judge_dict: judge3,condition_dict:dictPath+'BD_D_JQLYFSDM.js',multiple:true},
        {field:'SSRID',text:'送审人ID',input:'textbox',judge_dict: judge1},
        {field:'SSR_XM',text:'送审人姓名',input:'textbox',judge_dict: judge1},
        {field:'JZJQZTDM',text:'经侦警情状态',input:'combobox',judge_dict: judge3,condition_dict:dictPath+'BD_D_JZJQZTDM.js',multiple:true},
        {field:'CJQK',text:'处警情况',input:'textbox',judge_dict: judge1},

     
    ],
    TB_JQ_XYR_type : 'TB_JQ_XYR',
    TB_JQ_XYR_title : '嫌疑人信息',
    TB_JQ_XYR_init : [],    //默认显示的查询条件
    TB_JQ_XYR : [
        {field:'XXZJBH',text:'信息主键编号',input:'textbox',judge_dict: judge1},
        {field:'JQ_XXZJBH',text:'警情_信息主键编号',input:'textbox',judge_dict: judge1},
        {field:'ASJXGRYBH',text:'案事件相关人员编号',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_XYRDAZTDM',text:'嫌疑人_嫌疑人到案状态',input:'combobox',judge_dict: judge3,condition_dict:dictPath+'GA_D_DAZTDM.js',multiple:true},
        {field:'FZXYR_RSQZCSDM',text:'嫌疑人_人身强制措施',input:'combobox',judge_dict: judge3,condition_dict:dictPath+'GA_D_XSAJRSQZCSDM.js',multiple:true},
        {field:'FZXYR_CQQZCSSJ',text:'嫌疑人_采取强制措施时间',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_GTFZFZXYRSADWZYDM',text:'嫌疑人_共同犯罪犯罪嫌疑人涉案地位作用',input:'combobox',judge_dict: judge3,condition_dict:dictPath+'GA_D_GTFZFZXYRSADWZYDM.js',multiple:true},
        {field:'FZXYR_ZTRYBH',text:'嫌疑人_在逃人员编号',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_SFSZRY_PDBZ',text:'嫌疑人_是否收赃人员_判断标识',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_SFTAZS_PDBZ',text:'嫌疑人_是否投案自首_判断标识',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_SFSWZT_PDBZ',text:'嫌疑人_是否上网追逃_判断标识',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_XM',text:'嫌疑人_姓名',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_CYM',text:'嫌疑人_曾用名',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_BMCH',text:'嫌疑人_别名',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_CYZJ_CYZJDM',text:'嫌疑人_常用证件_常用证件代码',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_CYZJ_DMBCMS',text:'嫌疑人_常用证件_代码补充描述',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_CYZJ_ZJHM',text:'嫌疑人_常用证件_证件号码',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_CSRQ',text:'嫌疑人_出生日期',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_XBDM',text:'嫌疑人_性别代码',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_GJDM',text:'嫌疑人_国籍代码',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_JGDM',text:'嫌疑人_籍贯省市县代码',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_MZDM',text:'嫌疑人_民族代码',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_CSD_GJHDQDM',text:'嫌疑人_出生地_国家和地区代码',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_CSD_XZQHDM',text:'嫌疑人_出生地_行政区划代码',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_CSD_DZMC',text:'嫌疑人_出生地_地址名称',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_HJDZ_XZQHDM',text:'嫌疑人_户籍地址_行政区划代码',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_HJDZ_DZMC',text:'嫌疑人_户籍地址_地址名称',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_XZZ_XZQHDM',text:'嫌疑人_现住址_行政区划代码',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_XZZ_DZMC',text:'嫌疑人_现住址_地址名称',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_JWZZ_GJHDQDM',text:'嫌疑人_境外住址_国家和地区代码',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_JWZZ_DZMC',text:'嫌疑人_境外住址_地址名称',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_SG',text:'嫌疑人_身高',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_TZ',text:'嫌疑人_体重',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_ZC',text:'嫌疑人_足长',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_TMTZMS',text:'嫌疑人_体貌特征描述',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_TBBJMS',text:'嫌疑人_体表标记描述',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_RQTTZ_JYQK',text:'嫌疑人_人其他特征_简要情况',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_GZDW',text:'嫌疑人_工作单位',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_ZJXYDM',text:'嫌疑人_宗教信仰代码',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_ZZMMDM',text:'嫌疑人_政治面貌代码',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_XLDM',text:'嫌疑人_学历代码',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_JYZKDM',text:'嫌疑人_婚姻状况代码',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_BYZKDM',text:'嫌疑人_兵役状况代码',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_ZYLBDM',text:'嫌疑人_职业_职业类别代码',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_ZYDMBCMS',text:'嫌疑人_职业_代码补充描述',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_ASJXGRYSF_ASJXGRYSFDM',text:'嫌疑人_案事件相关人员身份_案事件相关人员身份代码',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_ASJXGRYSF_DMBCMS',text:'嫌疑人_案事件相关人员身份_代码补充描述',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_FZXYRTSZC_FZXYRTSZCDM',text:'嫌疑人_犯罪嫌疑人特殊专长_犯罪嫌疑人特殊专长代码',input:'combobox',judge_dict: judge3,condition_dict:dictPath+'GA_D_FZXYRTSZCDM.js',multiple:true},
        {field:'FZXYR_FZXYRTSZC_DMBCMS',text:'嫌疑人_犯罪嫌疑人特殊专长_代码补充描述',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_JL',text:'嫌疑人_简历',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_GRAHJHDTD_JYQK',text:'嫌疑人_个人爱好及活动特点_简要情况',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_WFFZJLMS',text:'嫌疑人_违法犯罪经历描述',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_SFYXDS_PDBZ',text:'嫌疑人_是否有吸毒史_判断标识',input:'combobox',judge_dict: judge3,condition_dict:dictPath+'DB_D_SFJZRYSF.js',multiple:true},
        {field:'FZXYR_LYDP_SAWPDM',text:'嫌疑人_滥用毒品_涉案物品代码',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_LYDP_DMBCMS',text:'嫌疑人_滥用毒品_代码补充描述',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_SFHY_PDBZ',text:'嫌疑人_是否怀孕_判断标识',input:'textbox',input:'combobox',judge_dict: judge3,condition_dict:dictPath+'DB_D_SFJZRYSF.js',multiple:true},
        {field:'FZXYR_DPNJSFYX_PDBZ',text:'嫌疑人_毒品尿检是否阳性_判断标识',input:'combobox',judge_dict: judge3,condition_dict:dictPath+'DB_D_SFJZRYSF.js',multiple:true},
        {field:'FZXYR_SFAZBBDXDZ_PDBZ',text:'嫌疑人_是否艾滋病病毒携带者_判断标识',input:'combobox',judge_dict: judge3,condition_dict:dictPath+'DB_D_SFJZRYSF.js',multiple:true},
        {field:'FZXYR_SFZDJBHZ_PDBZ',text:'嫌疑人_是否重大疾病患者_判断标识',input:'combobox',judge_dict: judge3,condition_dict:dictPath+'DB_D_SFJZRYSF.js',multiple:true},
        {field:'FZXYR_SFJSBR_PDBZ',text:'嫌疑人_是否精神病人_判断标识',input:'combobox',judge_dict: judge3,condition_dict:dictPath+'DB_D_SFJZRYSF.js',multiple:true},
        {field:'FZXYR_XDWP_JYQK',text:'嫌疑人_携带物品_简要情况',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_SZZWBH',text:'嫌疑人_十指指纹编号',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_RYDNABH',text:'嫌疑人_人员DNA编号',input:'textbox',judge_dict: judge1},
        {field:'FZXYR_BZ',text:'嫌疑人_备注',input:'textbox',judge_dict: judge1},
        {field:'GXPCSDM',text:'所属派出所代码',input:'textbox',judge_dict: judge1},
        {field:'GXFXJDM',text:'所属分县局代码',input:'textbox',judge_dict: judge1},
        {field:'GXSJDM',text:'所属市局代码',input:'textbox',judge_dict: judge1},
        {field:'XT_LRSJ',text:'录入时间',input:'textbox',judge_dict: judge1},
        {field:'XT_LRRXM',text:'录入人姓名',input:'textbox',judge_dict: judge1},
        {field:'XT_LRRID',text:'录入人ID',input:'textbox',judge_dict: judge1},
        {field:'XT_LRRBM',text:'录入人部门',input:'textbox',judge_dict: judge1},
        {field:'XT_LRRBMID',text:'录入人部门ID',input:'textbox',judge_dict: judge1},
        {field:'XT_LRIP',text:'录入IP',input:'textbox',judge_dict: judge1},
        {field:'XT_ZHXGSJ',text:'最后修改时间',input:'datebox',judge_dict: judge2,formatter:'date10'},
        {field:'XT_ZHXGRXM',text:'最后修改人姓名',input:'textbox',judge_dict: judge1},
        {field:'XT_ZHXGRID',text:'最后修改人ID',input:'textbox',judge_dict: judge1},
        {field:'XT_ZHXGRBM',text:'最后修改人部门',input:'textbox',judge_dict: judge1},
        {field:'XT_ZHXGRBMID',text:'最后修改人部门ID',input:'textbox',judge_dict: judge1},
        {field:'XT_ZHXGIP',text:'最后修改IP',input:'textbox',judge_dict: judge1},
        {field:'XT_ZXBZ',text:'注销标志',input:'textbox',judge_dict: judge1},
        {field:'XT_ZXYY',text:'注销原因',input:'textbox',judge_dict: judge1},
        {field:'XT_ZXYYBZ',text:'注销原因备注',input:'textbox',judge_dict: judge1},

    ]
};


