/*配置说明
* 1.不同查询模块均使用相同的index_config.html中的内容,改革文件名即可
* 2.html文件下方引用不同的search_config_模块名称.js
* 3.在search_config_模块名称.js中配置页面查询参数和展示参数
*/
var dictPath = portal + '/common/dict/';
var search_config_arr = ["TB_ST_XZASJ", "TB_ST_XZFYJBXX"];
//查询条件配置
var search_config = {
    //查询接口地址
    url: compositQueryPath,
    basePath: basePath,
    export_url: basePath + 'cetcQuery/exportExcel2003/zhcxXzaj',
    main_type: 'tb_st_xzasj',
    primary_key: 'XXZJBH',//主键

    //页面标题名称
    query_title: '行政案件',
    sysType: 'xzaj',

    //基本信息查询条件和展示项配置
    TB_ST_XZASJ_type: 'TB_ST_XZASJ',
    TB_ST_XZASJ_title: '行政案件-基本信息',
    TB_ST_XZASJ_init: ['AJMC', 'FXASJSJ', 'SLDW_GAJGMC'],//默认显示的查询条件
    TB_ST_XZASJ: [
        // {field: 'XXZJBH', text: '信息主键编号', input: '', judge_dict: judge},
        // {field: 'ASJBH', text: '案事件编号(业务)', input: '', judge_dict: judge},
        // {field: 'JJBH', text: '接警编号(业务)', input: '', judge_dict: judge},
        // {field: 'XCKYBH', text: '现场勘验编号', input: '', judge_dict: judge},
        {
            field: 'ASJLYDM',
            text: '案事件来源',
            input: 'combobox',
            condition_dict: dictPath + 'GA_D_ASJLYFLDM.js',
            judge_dict: judge3
        },
        {
            field: 'XZJQLBDM',
            text: '行政警情类别',
            input: 'combobox',
            condition_dict: dictPath + 'BD_D_JQLBDM.js',
            judge_dict: judge3
        },
        {
            field: 'AJLBDM',
            text: '案件类别',
            input: 'combobox',
            condition_dict: dictPath + 'GA_D_XZAJLBDM.js',
            judge_dict: judge3
        },
        {field: 'ZATZ_JYQK', text: '作案特征', input: 'textbox', judge_dict: judge1},
        {field: 'AJMC', text: '案件名称', input: 'textbox', judge_dict: judge1},
        {field: 'FXASJSJ', text: '发现案事件时间', input: 'datebox', judge_dict: judge2},
        {
            field: 'FXASJDD_XZQHDM',
            text: '发现案件地点行政区划',
            input: 'combobox',
            condition_dict: dictPath + 'GB_D_NEWXZQHDM.js',
            judge_dict: judge3
        },
        {field: 'FXASJDD_DZMC', text: '发现案件地点地址名称', input: 'textbox', judge_dict: judge1},
        // {field: 'FXASJDD_DZID', text: '发现案事件地点_地址ID', input: '', judge_dict: judge},
        {field: 'ASJFSSJ_ASJFSKSSJ', text: '案发开始时间', input: 'datebox', judge_dict: judge2},
        {field: 'ASJFSSJ_ASJFSJSSJ', text: '案发结束时间', input: 'datebox', judge_dict: judge2},
        {
            field: 'ASJFSDD_XZQHDM',
            text: '案发地点行政区划',
            input: 'combobox',
            condition_dict: dictPath + 'GB_D_NEWXZQHDM.js',
            judge_dict: judge3
        },
        {field: 'ASJFSDD_DZMC', text: '案发地点地址名称', input: 'textbox', judge_dict: judge1},
        {field: 'ASJFSDD_DQJD', text: '案事件发生地点_经度', input: 'textbox', judge_dict: judge3},
        {field: 'ASJFSDD_DQWD', text: '案事件发生地点_纬度', input: 'textbox', judge_dict: judge3},
        // {field: 'ASJFSDD_DZID', text: '案事件发生地点_地址ID', input: '', judge_dict: judge},
        {
            field: 'ASJFSDD_DYLBDM',
            text: '案发地点地域类别',
            input: 'combobox',
            condition_dict: dictPath + 'GA_D_DYLBDM.js',
            judge_dict: judge3
        },
        {
            field: 'ASJFSDD_SACS_SACSLBDM',
            text: '案发地点涉案场所',
            input: 'combobox',
            condition_dict: dictPath + 'GA_D_SACSFLDM.js',
            judge_dict: judge3
        },
        // {field: 'ASJFSDD_SACS_DMBCMS', text: '案事件发生地点_涉案场所_代码补充描述（华南）', input: '', judge_dict: judge},
        {field: 'JYAQ', text: '简要案情', input: 'textbox', judge_dict: judge1},
        {
            field: 'SFSQ_PDBZ',
            text: '是否涉枪',
            input: 'combobox',
            condition_dict: dictPath + 'BD_D_SFDM.js',
            judge_dict: judge3
        },
        {
            field: 'SFSB_PDBZ',
            text: '是否涉爆',
            input: 'combobox',
            condition_dict: dictPath + 'BD_D_SFDM.js',
            judge_dict: judge3
        },
        {
            field: 'SFSW_PDBZ',
            text: '是否涉外',
            input: 'combobox',
            condition_dict: dictPath + 'BD_D_SFDM.js',
            judge_dict: judge3
        },
        {field: 'SWASJSWQK', text: '涉外情况', input: 'textbox', judge_dict: judge1},
        {field: 'SSWPQX_JYQK', text: '损失物品去向', input: 'textbox', judge_dict: judge1},
        {field: 'XCKYWP_JYQK', text: '现场可疑物品', input: 'textbox', judge_dict: judge1},
        {field: 'FXXS_JYQK', text: '发现线索', input: 'textbox', judge_dict: judge1},
        {field: 'ASJSSRY_RS', text: '案事件受伤人数', input: 'numberbox', judge_dict: judge3},
        {field: 'ASJSSCW_JYQK', text: '案事件损失财物', input: 'textbox', judge_dict: judge1},
        {field: 'ASJGZWP_JYQK', text: '案事件管制物品', input: 'textbox', judge_dict: judge1},
        {field: 'SSJZRMBY', text: '损失价值（人民币元）', input: 'numberbox', judge_dict: judge3},
        {field: 'SLSJ', text: '受理时间', input: 'datebox', judge_dict: judge2},
        // {field: 'SLDW_GAJGJGDM', text: '受理单位_公安机关机构代码', input: '', judge_dict: judge},
        {field: 'SLDW_GAJGMC', text: '受理公安机关名称', input: 'textbox', judge_dict: judge1},
        {field: 'SJCWJZRMBY', text: '收缴财物价值（人民币元）', input: 'numberbox', judge_dict: judge3},
        {field: 'YSSCQSRQ', text: '移送日期', input: 'datebox', judge_dict: judge2},
        {field: 'ZBR_XM', text: '主办人姓名', input: 'textbox', judge_dict: judge1},
        {field: 'ZBR_GMSFHM', text: '主办人公民身份号码', input: 'textbox', judge_dict: judge1},
        {field: 'ZBR_LXDH', text: '主办人联系电话', input: 'textbox', judge_dict: judge1},
        {field: 'XBR_XM', text: '协办人姓名', input: 'textbox', judge_dict: judge1},
        {field: 'XBR_GMSFHM', text: '协办人公民身份号码', input: 'textbox', judge_dict: judge1},
        {field: 'XBR_LXDH', text: '协办人联系电话', input: 'textbox', judge_dict: judge1},
        {
            field: 'AJYWZTDM',
            text: '案件业务状态',
            input: 'combobox',
            condition_dict: dictPath + 'BD_D_AJZT.js',
            judge_dict: judge3
        },
        {
            field: 'SFCB',
            text: '是否串并',
            input: 'combobox',
            condition_dict: dictPath + 'BD_D_SFDM.js',
            judge_dict: judge3
        },
        {field: 'JJSJ', text: '接警时间', input: 'datebox', judge_dict: judge2},
        {
            field: 'JJFS',
            text: '接警方式',
            input: 'combobox',
            condition_dict: dictPath + 'BD_D_BJFSDM.js',
            judge_dict: judge3
        },
        {field: 'ZAZT', text: '作案状态', input: 'textbox', judge_dict: judge1},
        {field: 'SSSQ', text: '所属社区', input: 'textbox', judge_dict: judge1},
        {field: 'SAZZ', text: '涉案总值', input: 'numberbox', judge_dict: judge3},
        {field: 'JASJ', text: '结案时间', input: 'datebox', judge_dict: judge2},
        // {field: 'SECURITYGRADE', text: '密级', input: '', judge_dict: judge},
        {
            field: 'SYFL',
            text: '适用法律',
            input: 'combobox',
            condition_dict: dictPath + 'BD_D_SYFL.js',
            judge_dict: judge3
        },
        {field: 'SBQK', text: '涉爆情况', input: 'textbox', judge_dict: judge1},
        {field: 'SQQK', text: '涉枪情况', input: 'textbox', judge_dict: judge1},
        // {field: 'GXPCSDM', text: '所属派出所代码', input: '', judge_dict: judge},
        // {field: 'GXFXJDM', text: '所属分县局代码', input: '', judge_dict: judge},
        // {field: 'GXSJDM', text: '所属市局代码', input: '', judge_dict: judge},
        // {field: 'OLD_SYSTEMID', text: '老警综-B_ASJ_AJ表-系统编号', input: '', judge_dict: judge},
        // {field: 'AJYWZTMXDM', text: '案件业务状态明细代码', input: '', judge_dict: judge},
        {field: 'BJSJ', text: '报警时间', input: 'datebox', judge_dict: judge2},
        {
            field: 'AJJADM', 
            text: '案件结案', 
            input: 'combobox',
            condition_dict: dictPath + 'BD_D_AJJADM.js',
            judge_dict: judge3
        },
        // {field: 'ASJFSDD_SFBZ', text: '案发地点是否标准地址', input: '', judge_dict: judge},
        {field: 'BADW_GAJGMC', text: '办案机构公安机关名称', input: 'textbox', judge_dict: judge1},
        // {field: 'BADW_GAJGJGDM', text: '办案机构公安机关机构代码', input: '', judge_dict: judge},
        // {field: 'SFZA', text: '是否转案', input: '', judge_dict: judge},
        //---------------------
        {field: 'XT_LRSJ', text: '录入时间', input: 'datebox', judge_dict: judge2},
        {field: 'XT_LRRXM', text: '录入人姓名', input: 'textbox', judge_dict: judge1},
        // {field: 'XT_LRRID', text: '录入人ID', input: '', judge_dict: judge},
        // {field: 'XT_LRRBM', text: '录入人部门', input: '', judge_dict: judge},
        {
            field: 'XT_LRRBMID',
            text: '录入人部门',
            input: 'textbox_org',
            judge_dict: judge12,
            isOrganization: true,
            lishu: {sj: 'XT_LRRBMID_SJ', fxj: 'XT_LRRBMID_FXJ', pcs: 'XT_LRRBMID_PCS', zrq: 'XT_LRRBMID_ZRQ'}
        },
        // {field: 'XT_LRIP', text: '录入IP', input: '', judge_dict: judge},
        {field: 'XT_ZHXGSJ', text: '最后修改时间', input: 'datebox', judge_dict: judge2},
        {field: 'XT_ZHXGRXM', text: '最后修改人姓名', input: 'textbox', judge_dict: judge1},
        // {field: 'XT_ZHXGRID', text: '最后修改人ID', input: '', judge_dict: judge},
        // {field: 'XT_ZHXGRBM', text: '最后修改人部门', input: '', judge_dict: judge},
        {
            field: 'XT_ZHXGRBMID',
            text: '最后修改人部门',
            input: 'textbox_org',
            judge_dict: judge12,
            isOrganization: true,
            lishu: {sj: 'XT_ZHXGRBMID_SJ', fxj: 'XT_ZHXGRBMID_FXJ', pcs: 'XT_ZHXGRBMID_PCS', zrq: 'XT_ZHXGRBMID_ZRQ'}
        },
        // {field: 'XT_ZHXGIP', text: '最后修改IP', input: '', judge_dict: judge},
        {
            field: 'XT_ZXBZ',
            text: '注销标志',
            input: 'combobox',
            judge_dict: judge3,
            condition_dict: dictPath + 'BD_D_ZXBZDM.js',
            multiple: true
        },
        // {field: 'XT_ZXYY', text: '注销原因', input: '', judge_dict: judge},
        {field: 'XT_ZXYYBZ', text: '注销原因', input: 'textbox', judge_dict: judge1}
    ],

    TB_ST_XZFYJBXX_type: 'TB_ST_XZFYJBXX',
    TB_ST_XZFYJBXX_title: '行政案件-复议信息',
    TB_ST_XZFYJBXX_init: [],
    TB_ST_XZFYJBXX: [
        // {field: 'XXZJBH', text: '信息主键编号', input: '', judge_dict: judge},
        // {field: 'AJ_XXZJBH', text: '案件_信息主键编号', input: '', judge_dict: judge},
        // {field: 'ASJBH', text: '案事件编号', input: '', judge_dict: judge},
        {
            field: 'AJLBDM', 
            text: '案件类别', 
            input: 'combobox',
            condition_dict: dictPath + 'GA_D_XZAJLBDM.js',
            judge_dict: judge3
        },
        {field: 'AJMC', text: '案件名称', input: 'textbox', judge_dict: judge1},
        {
            field: 'CYZJ_CYZJDM', 
            text: '常用证件', 
            input: 'combobox',
            condition_dict: dictPath + 'GA_D_CYZJDM.js',
            judge_dict: judge3
        },
        {field: 'CYZJ_ZJHM', text: '证件号码', input: 'textbox', judge_dict: judge1},
        {field: 'SQRXM', text: '申请人姓名', input: 'textbox', judge_dict: judge1},
        {field: 'BSQBM', text: '被申请部门', input: 'textbox', judge_dict: judge1},
        // {field: 'BSQBMID', text: '被申请部门ID', input: '', judge_dict: judge},
        {field: 'SDSJ', text: '收到时间', input: 'datebox', judge_dict: judge2},
        {field: 'XZXW', text: '行政行为', input: 'textbox', judge_dict: judge1},
        {field: 'CLJG', text: '处理结果', input: 'textbox', judge_dict: judge1},
        {field: 'WSBH', text: '文书编号', input: 'textbox', judge_dict: judge1},
        {field: 'CBRXM', text: '承办人姓名', input: 'textbox', judge_dict: judge1},
        // {field: 'CBRID', text: '承办人ID', input: '', judge_dict: judge},
        {field: 'BJSJ', text: '办结时间', input: 'datebox', judge_dict: judge2},

        {field: 'XT_LRSJ', text: '录入时间', input: 'datebox', judge_dict: judge2},
        {field: 'XT_LRRXM', text: '录入人姓名', input: 'textbox', judge_dict: judge1},
        // {field: 'XT_LRRID', text: '录入人ID', input: '', judge_dict: judge},
        // {field: 'XT_LRRBM', text: '录入人部门', input: '', judge_dict: judge},
        {
            field: 'XT_LRRBMID',
            text: '录入人部门',
            input: 'textbox_org',
            judge_dict: judge12,
            isOrganization: true,
            lishu: {sj: 'XT_LRRBMID_SJ', fxj: 'XT_LRRBMID_FXJ', pcs: 'XT_LRRBMID_PCS', zrq: 'XT_LRRBMID_ZRQ'}
        },
        // {field: 'XT_LRIP', text: '录入IP', input: '', judge_dict: judge},
        {field: 'XT_ZHXGSJ', text: '最后修改时间', input: 'datebox', judge_dict: judge2},
        {field: 'XT_ZHXGRXM', text: '最后修改人姓名', input: 'textbox', judge_dict: judge1},
        // {field: 'XT_ZHXGRID', text: '最后修改人ID', input: '', judge_dict: judge},
        // {field: 'XT_ZHXGRBM', text: '最后修改人部门', input: '', judge_dict: judge},
        {
            field: 'XT_ZHXGRBMID',
            text: '最后修改人部门',
            input: 'textbox_org',
            judge_dict: judge12,
            isOrganization: true,
            lishu: {sj: 'XT_ZHXGRBMID_SJ', fxj: 'XT_ZHXGRBMID_FXJ', pcs: 'XT_ZHXGRBMID_PCS', zrq: 'XT_ZHXGRBMID_ZRQ'}
        },
        // {field: 'XT_ZHXGIP', text: '最后修改IP', input: '', judge_dict: judge},
        {
            field: 'XT_ZXBZ',
            text: '注销标志',
            input: 'combobox',
            judge_dict: judge3,
            condition_dict: dictPath + 'BD_D_ZXBZDM.js',
            multiple: true
        },
        // {field: 'XT_ZXYY', text: '注销原因', input: '', judge_dict: judge},
        {field: 'XT_ZXYYBZ', text: '注销原因', input: 'textbox', judge_dict: judge1},
        
        {
            field: 'FYZT', 
            text: '复议状态', 
            input: 'combobox',
            condition_dict: dictPath + 'BD_D_SFDM.js',
            judge_dict: judge3
        }
    ]
};

//以下为测试数据
var search_result_test = {
    "count": 123456,
    "msg": "success",
    "type": null,
    "took": 666,
    "result": [
        {
            "XXZJBH": "9e03f2b941304330a999ec44eecebd88",
            "ASJBH": "A5110114000002016111441",
            "JJBH": null,
            "XCKYBH": null,
            "ASJLYDM": null,
            "XZJQLBDM": null,
            "AJLBDM": "300000",
            "ZATZ_JYQK": null,
            "AJMC": "121212",
            "FXASJSJ": "2016-11-24T00:00:00.000+0800",
            "FXASJDD_XZQHDM": null,
            "FXASJDD_DZMC": null,
            "FXASJDD_DZID": null,
            "ASJFSSJ_ASJFSKSSJ": "2016-11-24T00:00:00.000+0800",
            "ASJFSSJ_ASJFSJSSJ": "2016-11-24T00:00:00.000+0800",
            "ASJFSDD_XZQHDM": null,
            "ASJFSDD_DZMC": "内江",
            "ASJFSDD_DQJD": null,
            "ASJFSDD_DQWD": null,
            "ASJFSDD_DZID": null,
            "ASJFSDD_DYLBDM": "1010",
            "ASJFSDD_SACS_SACSLBDM": "1000",
            "ASJFSDD_SACS_DMBCMS": null,
            "JYAQ": "121212121212",
            "SFSQ_PDBZ": null,
            "SFSB_PDBZ": null,
            "SFSW_PDBZ": null,
            "SWASJSWQK": null,
            "SSWPQX_JYQK": null,
            "XCKYWP_JYQK": null,
            "FXXS_JYQK": null,
            "ASJSSRY_RS": null,
            "ASJSSCW_JYQK": null,
            "ASJGZWP_JYQK": null,
            "SSJZRMBY": null,
            "SLSJ": null,
            "SLDW_GAJGJGDM": null,
            "SLDW_GAJGMC": null,
            "SJCWJZRMBY": null,
            "YSSCQSRQ": null,
            "ZBR_XM": null,
            "ZBR_GMSFHM": null,
            "ZBR_LXDH": null,
            "XBR_XM": null,
            "XBR_GMSFHM": null,
            "XBR_LXDH": null,
            "AJYWZTDM": "00",
            "SFCB": null,
            "JJSJ": "2016-11-24T00:00:00.000+0800",
            "JJFS": "4",
            "ZAZT": null,
            "SSSQ": null,
            "SAZZ": null,
            "JASJ": null,
            "SECURITYGRADE": null,
            "SYFL": null,
            "XT_LRSJ": "2016-11-24T11:10:21.000+0800",
            "XT_LRRXM": "吴鹏",
            "XT_LRRID": "511011198212301750",
            "XT_LRRBM": "四川省内江市公安局东兴区分局东兴派出所",
            "XT_LRRBMID": "511011400000",
            "XT_LRIP": "172.29.214.59",
            "XT_ZHXGSJ": "2016-11-24T11:10:21.000+0800",
            "XT_ZHXGRXM": "吴鹏",
            "XT_ZHXGRID": "511011198212301750",
            "XT_ZHXGRBM": "四川省内江市公安局东兴区分局东兴派出所",
            "XT_ZHXGRBMID": "511011400000",
            "XT_ZHXGIP": "172.29.214.59",
            "XT_ZXBZ": "0",
            "XT_ZXYY": null,
            "XT_ZXYYBZ": null,
            "SBQK": null,
            "SQQK": null,
            "GXPCSDM": null,
            "GXFXJDM": null,
            "GXSJDM": null,
            "OLD_SYSTEMID": null,
            "AJYWZTMXDM": "00",
            "BJSJ": null,
            "AJJADM": null,
            "ASJFSDD_SFBZ": "1",
            "BADW_GAJGMC": null,
            "BADW_GAJGJGDM": null,
            "SFZA": null
        },
        {
            "XXZJBH": "e41414f1961a4c45842cac3388907d39",
            "ASJBH": "A5110114000002016122103",
            "JJBH": "5110114000002016120800014",
            "XCKYBH": null,
            "ASJLYDM": null,
            "XZJQLBDM": "10101",
            "AJLBDM": null,
            "ZATZ_JYQK": null,
            "AJMC": null,
            "FXASJSJ": "2016-12-08T00:00:00.000+0800",
            "FXASJDD_XZQHDM": null,
            "FXASJDD_DZMC": null,
            "FXASJDD_DZID": "511002510000201305070924185465",
            "ASJFSSJ_ASJFSKSSJ": "2016-12-01T00:00:00.000+0800",
            "ASJFSSJ_ASJFSJSSJ": "2016-12-02T00:00:00.000+0800",
            "ASJFSDD_XZQHDM": null,
            "ASJFSDD_DZMC": "四川省内江市市中区白电路1号11栋1单元1楼1号",
            "ASJFSDD_DQJD": null,
            "ASJFSDD_DQWD": null,
            "ASJFSDD_DZID": null,
            "ASJFSDD_DYLBDM": null,
            "ASJFSDD_SACS_SACSLBDM": null,
            "ASJFSDD_SACS_DMBCMS": null,
            "JYAQ": null,
            "SFSQ_PDBZ": null,
            "SFSB_PDBZ": null,
            "SFSW_PDBZ": null,
            "SWASJSWQK": null,
            "SSWPQX_JYQK": null,
            "XCKYWP_JYQK": null,
            "FXXS_JYQK": null,
            "ASJSSRY_RS": null,
            "ASJSSCW_JYQK": null,
            "ASJGZWP_JYQK": null,
            "SSJZRMBY": null,
            "SLSJ": "2016-12-27T00:00:00.000+0800",
            "SLDW_GAJGJGDM": "511011400000",
            "SLDW_GAJGMC": "四川省内江市公安局东兴区分局东兴派出所",
            "SJCWJZRMBY": null,
            "YSSCQSRQ": null,
            "ZBR_XM": null,
            "ZBR_GMSFHM": null,
            "ZBR_LXDH": null,
            "XBR_XM": null,
            "XBR_GMSFHM": null,
            "XBR_LXDH": null,
            "AJYWZTDM": "01",
            "SFCB": null,
            "JJSJ": "2016-12-08T00:00:00.000+0800",
            "JJFS": "4",
            "ZAZT": null,
            "SSSQ": null,
            "SAZZ": null,
            "JASJ": null,
            "SECURITYGRADE": null,
            "SYFL": null,
            "XT_LRSJ": "2016-12-27T11:19:17.000+0800",
            "XT_LRRXM": "吴鹏",
            "XT_LRRID": "511011198212301750",
            "XT_LRRBM": "四川省内江市公安局东兴区分局东兴派出所",
            "XT_LRRBMID": "511011400000",
            "XT_LRIP": null,
            "XT_ZHXGSJ": "2016-12-27T11:19:17.000+0800",
            "XT_ZHXGRXM": "吴鹏",
            "XT_ZHXGRID": "511011198212301750",
            "XT_ZHXGRBM": "四川省内江市公安局东兴区分局东兴派出所",
            "XT_ZHXGRBMID": "511011400000",
            "XT_ZHXGIP": null,
            "XT_ZXBZ": "0",
            "XT_ZXYY": null,
            "XT_ZXYYBZ": null,
            "SBQK": null,
            "SQQK": null,
            "GXPCSDM": null,
            "GXFXJDM": null,
            "GXSJDM": null,
            "OLD_SYSTEMID": null,
            "AJYWZTMXDM": "01",
            "BJSJ": null,
            "AJJADM": null,
            "ASJFSDD_SFBZ": "1",
            "BADW_GAJGMC": null,
            "BADW_GAJGJGDM": null,
            "SFZA": null
        },
        {
            "XXZJBH": "9ab28eec66d14b9bac3edffb06c3d1aa",
            "ASJBH": "A5110114000002017012446",
            "JJBH": "5110114000002017010900002",
            "XCKYBH": null,
            "ASJLYDM": null,
            "XZJQLBDM": "20101",
            "AJLBDM": null,
            "ZATZ_JYQK": null,
            "AJMC": null,
            "FXASJSJ": "2017-01-09T00:00:00.000+0800",
            "FXASJDD_XZQHDM": null,
            "FXASJDD_DZMC": null,
            "FXASJDD_DZID": "0f18707d4cfa492e884aaadb4b23fc5b",
            "ASJFSSJ_ASJFSKSSJ": "2017-01-09T00:00:00.000+0800",
            "ASJFSSJ_ASJFSJSSJ": "2017-01-09T00:00:00.000+0800",
            "ASJFSDD_XZQHDM": null,
            "ASJFSDD_DZMC": "四川省成都市成都市泉水东路,",
            "ASJFSDD_DQJD": null,
            "ASJFSDD_DQWD": null,
            "ASJFSDD_DZID": null,
            "ASJFSDD_DYLBDM": null,
            "ASJFSDD_SACS_SACSLBDM": null,
            "ASJFSDD_SACS_DMBCMS": null,
            "JYAQ": null,
            "SFSQ_PDBZ": null,
            "SFSB_PDBZ": null,
            "SFSW_PDBZ": null,
            "SWASJSWQK": null,
            "SSWPQX_JYQK": null,
            "XCKYWP_JYQK": null,
            "FXXS_JYQK": null,
            "ASJSSRY_RS": null,
            "ASJSSCW_JYQK": null,
            "ASJGZWP_JYQK": null,
            "SSJZRMBY": null,
            "SLSJ": "2017-01-13T00:00:00.000+0800",
            "SLDW_GAJGJGDM": "511011400000",
            "SLDW_GAJGMC": "四川省内江市公安局东兴区分局东兴派出所",
            "SJCWJZRMBY": null,
            "YSSCQSRQ": null,
            "ZBR_XM": null,
            "ZBR_GMSFHM": null,
            "ZBR_LXDH": null,
            "XBR_XM": null,
            "XBR_GMSFHM": null,
            "XBR_LXDH": null,
            "AJYWZTDM": "01",
            "SFCB": null,
            "JJSJ": "2017-01-09T00:00:00.000+0800",
            "JJFS": "2",
            "ZAZT": null,
            "SSSQ": null,
            "SAZZ": null,
            "JASJ": null,
            "SECURITYGRADE": null,
            "SYFL": null,
            "XT_LRSJ": "2017-01-13T14:21:43.000+0800",
            "XT_LRRXM": "吴鹏",
            "XT_LRRID": "511011198212301750",
            "XT_LRRBM": "四川省内江市公安局东兴区分局东兴派出所",
            "XT_LRRBMID": "511011400000",
            "XT_LRIP": null,
            "XT_ZHXGSJ": "2017-01-13T14:21:43.000+0800",
            "XT_ZHXGRXM": "吴鹏",
            "XT_ZHXGRID": "511011198212301750",
            "XT_ZHXGRBM": "四川省内江市公安局东兴区分局东兴派出所",
            "XT_ZHXGRBMID": "511011400000",
            "XT_ZHXGIP": null,
            "XT_ZXBZ": null,
            "XT_ZXYY": null,
            "XT_ZXYYBZ": null,
            "SBQK": null,
            "SQQK": null,
            "GXPCSDM": null,
            "GXFXJDM": null,
            "GXSJDM": null,
            "OLD_SYSTEMID": null,
            "AJYWZTMXDM": "01",
            "BJSJ": null,
            "AJJADM": null,
            "ASJFSDD_SFBZ": "1",
            "BADW_GAJGMC": null,
            "BADW_GAJGJGDM": null,
            "SFZA": null
        },
        {
            "XXZJBH": "833085c0f16944f7bddf5052e8d0fbac",
            "ASJBH": "A5110114000002016111081",
            "JJBH": "5110114000002016111300003",
            "XCKYBH": null,
            "ASJLYDM": null,
            "XZJQLBDM": "20201",
            "AJLBDM": null,
            "ZATZ_JYQK": null,
            "AJMC": null,
            "FXASJSJ": "2016-11-13T00:00:00.000+0800",
            "FXASJDD_XZQHDM": null,
            "FXASJDD_DZMC": null,
            "FXASJDD_DZID": "511002420000201412272251535681",
            "ASJFSSJ_ASJFSKSSJ": "2016-11-13T00:00:00.000+0800",
            "ASJFSSJ_ASJFSJSSJ": "2016-11-13T00:00:00.000+0800",
            "ASJFSDD_XZQHDM": null,
            "ASJFSDD_DZMC": "四川省内江市市中区阴家巷2号",
            "ASJFSDD_DQJD": null,
            "ASJFSDD_DQWD": null,
            "ASJFSDD_DZID": null,
            "ASJFSDD_DYLBDM": null,
            "ASJFSDD_SACS_SACSLBDM": null,
            "ASJFSDD_SACS_DMBCMS": null,
            "JYAQ": null,
            "SFSQ_PDBZ": null,
            "SFSB_PDBZ": null,
            "SFSW_PDBZ": null,
            "SWASJSWQK": null,
            "SSWPQX_JYQK": null,
            "XCKYWP_JYQK": null,
            "FXXS_JYQK": null,
            "ASJSSRY_RS": null,
            "ASJSSCW_JYQK": null,
            "ASJGZWP_JYQK": null,
            "SSJZRMBY": null,
            "SLSJ": "2016-11-14T00:00:00.000+0800",
            "SLDW_GAJGJGDM": "511011400000",
            "SLDW_GAJGMC": "四川省内江市公安局东兴区分局东兴派出所",
            "SJCWJZRMBY": null,
            "YSSCQSRQ": null,
            "ZBR_XM": null,
            "ZBR_GMSFHM": null,
            "ZBR_LXDH": null,
            "XBR_XM": null,
            "XBR_GMSFHM": null,
            "XBR_LXDH": null,
            "AJYWZTDM": "01",
            "SFCB": "2016-11-13T00:00:00.000+0800",
            "JJSJ": "4",
            "JJFS": null,
            "ZAZT": null,
            "SSSQ": null,
            "SAZZ": null,
            "JASJ": null,
            "SECURITYGRADE": null,
            "SYFL": null,
            "XT_LRSJ": "2016-11-14T09:55:20.000+0800",
            "XT_LRRXM": "吴鹏",
            "XT_LRRID": "511011198212301750",
            "XT_LRRBM": "四川省内江市公安局东兴区分局东兴派出所",
            "XT_LRRBMID": "511011400000",
            "XT_LRIP": null,
            "XT_ZHXGSJ": "2016-11-14T09:55:20.000+0800",
            "XT_ZHXGRXM": "吴鹏",
            "XT_ZHXGRID": "511011198212301750",
            "XT_ZHXGRBM": "四川省内江市公安局东兴区分局东兴派出所",
            "XT_ZHXGRBMID": "511011400000",
            "XT_ZHXGIP": null,
            "XT_ZXBZ": "0",
            "XT_ZXYY": null,
            "XT_ZXYYBZ": null,
            "SBQK": null,
            "SQQK": null,
            "GXPCSDM": null,
            "GXFXJDM": null,
            "GXSJDM": null,
            "OLD_SYSTEMID": null,
            "AJYWZTMXDM": "01",
            "BJSJ": null,
            "AJJADM": null,
            "ASJFSDD_SFBZ": "1",
            "BADW_GAJGMC": null,
            "BADW_GAJGJGDM": null,
            "SFZA": null
        },
        {
            "XXZJBH": "4e47cdebdef34dd7880da3b7a2649eac",
            "ASJBH": "A5110114000002016111245",
            "JJBH": "5110114000002016111800025",
            "XCKYBH": null,
            "ASJLYDM": null,
            "XZJQLBDM": "10101",
            "AJLBDM": null,
            "ZATZ_JYQK": null,
            "AJMC": null,
            "FXASJSJ": "2016-11-18T00:00:00.000+0800",
            "FXASJDD_XZQHDM": null,
            "FXASJDD_DZMC": null,
            "FXASJDD_DZID": "511011670000201410230959137646",
            "ASJFSSJ_ASJFSKSSJ": "2016-11-18T00:00:00.000+0800",
            "ASJFSSJ_ASJFSJSSJ": "2016-11-18T00:00:00.000+0800",
            "ASJFSDD_XZQHDM": null,
            "ASJFSDD_DZMC": "四川省内江市东兴区椑木镇椑峨路443号44栋4单元4楼1号",
            "ASJFSDD_DQJD": null,
            "ASJFSDD_DQWD": null,
            "ASJFSDD_DZID": null,
            "ASJFSDD_DYLBDM": null,
            "ASJFSDD_SACS_SACSLBDM": null,
            "ASJFSDD_SACS_DMBCMS": null,
            "JYAQ": null,
            "SFSQ_PDBZ": null,
            "SFSB_PDBZ": null,
            "SFSW_PDBZ": null,
            "SWASJSWQK": null,
            "SSWPQX_JYQK": null,
            "XCKYWP_JYQK": null,
            "FXXS_JYQK": null,
            "ASJSSRY_RS": null,
            "ASJSSCW_JYQK": null,
            "ASJGZWP_JYQK": null,
            "SSJZRMBY": null,
            "SLSJ": "2016-11-18T00:00:00.000+0800",
            "SLDW_GAJGJGDM": "511011400000",
            "SLDW_GAJGMC": "四川省内江市公安局东兴区分局东兴派出所",
            "SJCWJZRMBY": null,
            "YSSCQSRQ": null,
            "ZBR_XM": null,
            "ZBR_GMSFHM": null,
            "ZBR_LXDH": null,
            "XBR_XM": null,
            "XBR_GMSFHM": null,
            "XBR_LXDH": null,
            "AJYWZTDM": "01",
            "SFCB": "2016-11-13T00:00:00.000+0800",
            "JJSJ": "2",
            "JJFS": null,
            "ZAZT": null,
            "SSSQ": null,
            "SAZZ": null,
            "JASJ": null,
            "SECURITYGRADE": null,
            "SYFL": null,
            "XT_LRSJ": "2016-11-18T11:28:12.000+0800",
            "XT_LRRXM": "吴鹏",
            "XT_LRRID": "511011198212301750",
            "XT_LRRBM": "四川省内江市公安局东兴区分局东兴派出所",
            "XT_LRRBMID": "511011400000",
            "XT_LRIP": "127.0.0.1",
            "XT_ZHXGSJ": "2016-11-18T11:28:12.000+0800",
            "XT_ZHXGRXM": "吴鹏",
            "XT_ZHXGRID": "511011198212301750",
            "XT_ZHXGRBM": "四川省内江市公安局东兴区分局东兴派出所",
            "XT_ZHXGRBMID": "511011400000",
            "XT_ZHXGIP": "127.0.0.1",
            "XT_ZXBZ": "0",
            "XT_ZXYY": null,
            "XT_ZXYYBZ": null,
            "SBQK": null,
            "SQQK": null,
            "GXPCSDM": null,
            "GXFXJDM": null,
            "GXSJDM": null,
            "OLD_SYSTEMID": null,
            "AJYWZTMXDM": "01",
            "BJSJ": null,
            "AJJADM": null,
            "ASJFSDD_SFBZ": "1",
            "BADW_GAJGMC": null,
            "BADW_GAJGJGDM": null,
            "SFZA": null
        }
    ]
};