[{"id":"ROOT","text":"车辆类型","iconCls":"icon-treeroot1","children":

[
{"id":"B","text":"半挂车","py":"BGC","wb":"URL","state":"closed","children":[
{"id":"B11","text":"重型普通半挂车","py":"ZXPTBGC","wb":"TGUCURL"},
{"id":"B12","text":"重型厢式半挂车","py":"ZXXSBGC","wb":"TGDAURL"},
{"id":"B13","text":"重型罐式半挂车","py":"ZXGSBGC","wb":"TGRAURL"},
{"id":"B14","text":"重型平板半挂车","py":"ZXPBBGC","wb":"TGGSURL"},
{"id":"B15","text":"重型集装箱半挂车","py":"ZXJZXBGC","wb":"TGWUTURL"},
{"id":"B16","text":"重型自卸半挂车","py":"ZXZXBGC","wb":"TGTRURL"},
{"id":"B17","text":"重型特殊结构半挂车","py":"ZXTSJGBGC","wb":"TGTGXSURL"},
{"id":"B21","text":"中型普通半挂车","py":"ZXPTBGC","wb":"KGUCURL"},
{"id":"B22","text":"中型厢式半挂车","py":"ZXXSBGC","wb":"KGDAURL"},
{"id":"B23","text":"中型罐式半挂车","py":"ZXGSBGC","wb":"KGRAURL"},
{"id":"B24","text":"中型平板半挂车","py":"ZXPBBGC","wb":"KGGSURL"},
{"id":"B25","text":"中型集装箱半挂车","py":"ZXJZXBGC","wb":"KGWUTURL"},
{"id":"B26","text":"中型自卸半挂车","py":"ZXZXBGC","wb":"KGTRURL"},
{"id":"B27","text":"中型特殊结构半挂车","py":"ZXTSJGBGC","wb":"KGTGXSURL"},
{"id":"B31","text":"轻型普通半挂车","py":"QXPTBGC","wb":"LGUCURL"},
{"id":"B32","text":"轻型厢式半挂车","py":"QXXSBGC","wb":"LGDAURL"},
{"id":"B33","text":"轻型罐式半挂车","py":"QXGSBGC","wb":"LGRAURL"},
{"id":"B34","text":"轻型平板半挂车","py":"QXPBBGC","wb":"LGGSURL"},
{"id":"B35","text":"轻型自卸半挂车","py":"QXZXBGC","wb":"LGTRURL"}
]
},
{"id":"D","text":"电车","py":"DC","wb":"JL","state":"closed","children":[
{"id":"D11","text":"无轨电车","py":"WGDC","wb":"FLJL"},
{"id":"D12","text":"无轨电车","py":"WGDC","wb":"FLJL"}
]
},
{"id":"G","text":"全挂车","py":"QGC","wb":"WRL","state":"closed","children":[
{"id":"G11","text":"重型普通全挂车","py":"ZXPTQGC","wb":"TGUCWRL"},
{"id":"G12","text":"重型厢式全挂车","py":"ZXXSQGC","wb":"TGDAWRL"},
{"id":"G12","text":"重型厢式全挂车","py":"ZXXSQGC","wb":"TGDAWRL"},
{"id":"G13","text":"重型罐式全挂车","py":"ZXGSQGC","wb":"TGRAWRL"},
{"id":"G14","text":"重型平板全挂车","py":"ZXPBQGC","wb":"TGGSWRL"},
{"id":"G15","text":"重型集装箱全挂车","py":"ZXJZXQGC","wb":"TGWUTWRL"},
{"id":"G16","text":"重型自卸全挂车","py":"ZXZXQGC","wb":"TGTRWRL"},
{"id":"G21","text":"中型普通全挂车","py":"ZXPTQGC","wb":"KGUCWRL"},
{"id":"G22","text":"中型厢式全挂车","py":"ZXXSQGC","wb":"KGDAWRL"},
{"id":"G23","text":"中型罐式全挂车","py":"ZXGSQGC","wb":"KGRAWRL"},
{"id":"G24","text":"中型平板全挂车","py":"ZXPBQGC","wb":"KGGSWRL"},
{"id":"G25","text":"中型集装箱全挂车","py":"ZXJZXQGC","wb":"KGWUTWRL"},
{"id":"G26","text":"中型自卸全挂车","py":"ZXZXQGC","wb":"KGTRWRL"},
{"id":"G31","text":"轻型普通全挂车","py":"QXPTQGC","wb":"LGUCWRL"},
{"id":"G32","text":"轻型厢式全挂车","py":"QXXSQGC","wb":"LGDAWRL"},
{"id":"G33","text":"轻型罐式全挂车","py":"QXGSQGC","wb":"LGRAWRL"},
{"id":"G34","text":"轻型平板全挂车","py":"QXPBQGC","wb":"LGGSWRL"},
{"id":"G35","text":"轻型自卸全挂车","py":"QXZXQGC","wb":"LGTRWRL"}
]
},
{"id":"H","text":"货车","py":"HC","wb":"WL","state":"closed","children":[
{"id":"H11","text":"重型普通货车","py":"ZXPTHC","wb":"TGUCWL"},
{"id":"H12","text":"重型箱式货车","py":"ZXXSHC","wb":"TGTAWL"},
{"id":"H13","text":"重型封闭货车","py":"ZXFBHC","wb":"TGFUWL"},
{"id":"H14","text":"重型罐式货车","py":"ZXGSHC","wb":"TGRAWL"},
{"id":"H15","text":"重型平板货车","py":"ZXPBHC","wb":"TGGSWL"},
{"id":"H16","text":"重型集装厢车","py":"ZXJZXC","wb":"TGWUDL"},
{"id":"H17","text":"重型自卸货车","py":"ZXZXHC","wb":"TGTRWL"},
{"id":"H18","text":"重型特殊结构货车","py":"ZXTSJGHC","wb":"TGTGXSWL"},
{"id":"H21","text":"中型普通货车","py":"ZXPTHC","wb":"KGUCWL"},
{"id":"H22","text":"中型厢式货车","py":"ZXXSHC","wb":"KGDAWL"},
{"id":"H23","text":"中型封闭货车","py":"ZXFBHC","wb":"KGFUWL"},
{"id":"H24","text":"中型罐式货车","py":"ZXGSHC","wb":"KGRAWL"},
{"id":"H25","text":"中型平板货车","py":"ZXPBHC","wb":"KGGSWL"},
{"id":"H26","text":"中型集装厢车","py":"ZXJZXC","wb":"KGWUDL"},
{"id":"H27","text":"中型自卸货车","py":"ZXZXHC","wb":"KGTRWL"},
{"id":"H28","text":"中型特殊结构货车","py":"ZXTSJGHC","wb":"KGTGXSWL"},
{"id":"H31","text":"轻型普通货车","py":"QXPTHC","wb":"LGUCWL"},
{"id":"H32","text":"轻型厢式货车","py":"QXXSHC","wb":"LGDAWL"},
{"id":"H33","text":"轻型封闭货车","py":"QXFBHC","wb":"LGFUWL"},
{"id":"H34","text":"轻型罐式货车","py":"QXGSHC","wb":"LGRAWL"},
{"id":"H35","text":"轻型平板货车","py":"QXPBHC","wb":"LGGSWL"},
{"id":"H37","text":"轻型自卸货车","py":"QXZXHC","wb":"LGTRWL"},
{"id":"H38","text":"轻型特殊结构货车","py":"QXTSJGHC","wb":"LGTGXSWL"},
{"id":"H41","text":"微型普通货车","py":"WXPTHC","wb":"TGUCWL"},
{"id":"H42","text":"微型厢式货车","py":"WXXSHC","wb":"TGDAWL"},
{"id":"H43","text":"微型封闭货车","py":"WXFBHC","wb":"TGFUWL"},
{"id":"H44","text":"微型罐式货车","py":"WXGSHC","wb":"TGRAWL"},
{"id":"H45","text":"微型自卸货车","py":"WXZXHC","wb":"TGTRWL"},
{"id":"H46","text":"微型特殊结构货车","py":"WXTSJGHC","wb":"TGTGXSWL"},
{"id":"H51","text":"低速普通货车","py":"DSPTHC","wb":"WGUCWL"},
{"id":"H52","text":"低速厢式货车","py":"DSXSHC","wb":"WGDAWL"},
{"id":"H53","text":"低速罐式货车","py":"DSGSHC","wb":"WGRAWL"},
{"id":"H54","text":"低速自卸货车","py":"DSZXHC","wb":"WGTRWL"}
]
},
{"id":"J","text":"轮式机械","py":"LSJX","wb":"LASS","state":"closed","children":[
{"id":"J11","text":"轮式装载机械","py":"LSZZJX","wb":"LAUFSS"},
{"id":"J12","text":"轮式挖掘机械","py":"LSWJJX","wb":"LARRSS"},
{"id":"J13","text":"轮式平地机械","py":"LSPDJX","wb":"LAGFSS"}
]
},
{"id":"K","text":"客车","py":"KC","wb":"PL","state":"closed","children":[
{"id":"K11","text":"大型普通客车","py":"DXPTKC","wb":"DGUCPL"},
{"id":"K12","text":"大型双层客车","py":"DXSCKC","wb":"DGCNPL"},
{"id":"K13","text":"大型卧铺客车","py":"DXWPKC","wb":"DGAQPL"},
{"id":"K14","text":"大型快接客车","py":"DXKJKC","wb":"DGNRPL"},
{"id":"K15","text":"大型越野客车","py":"DXYYKC","wb":"DGFJPL"},
{"id":"K21","text":"中型普通客车","py":"ZXPTKC","wb":"KGUCPL"},
{"id":"K22","text":"中型双层客车","py":"ZXSCKC","wb":"KGCNPL"},
{"id":"K23","text":"中型卧铺客车","py":"ZXWPKC","wb":"KGAQPL"},
{"id":"K24","text":"中型铰接客车","py":"ZXJJKC","wb":"KGQRPL"},
{"id":"K25","text":"中型越野客车","py":"ZXYYKC","wb":"KGFJPL"},
{"id":"K31","text":"小型普通客车","py":"XXPTKC","wb":"IGUCPL"},
{"id":"K32","text":"小型越野客车","py":"XXYYKC","wb":"IGFJPL"},
{"id":"K33","text":"轿车","py":"JC","wb":"LL"},
{"id":"K41","text":"微型普通客车","py":"WXPTKC","wb":"TGUCPL"},
{"id":"K42","text":"微型越野客车","py":"WXYYKC","wb":"TGFJPL"},
{"id":"K43","text":"微型越野客车","py":"WXYYKC","wb":"TGFJPL"}
]
},
{"id":"M","text":"摩托车","py":"MTC","wb":"YRL","state":"closed","children":[
{"id":"M11","text":"普通正三轮摩托车","py":"PTZSLMTC","wb":"UCGDLYRL"},
{"id":"M12","text":"轻便正三轮摩托车","py":"QBZSLMTC","wb":"LWGDLYRL"},
{"id":"M13","text":"正三轮载客摩托车","py":"ZSLZKMTC","wb":"GDLFPYRL"},
{"id":"M14","text":"正三轮载货摩托车","py":"ZSLZHMTC","wb":"GDLFWYRL"},
{"id":"M15","text":"侧三轮摩托车","py":"CSLMTC","wb":"WDLYRL"},
{"id":"M21","text":"普通二轮摩托车","py":"PTELMTC","wb":"UCFLYRL"}
]
},
{"id":"N","text":"三轮汽车","py":"SLQC","wb":"DLIL","state":"closed","children":[
{"id":"N11","text":"三轮汽车","py":"SLQC","wb":"DLIL"}
]
},
{"id":"Q","text":"牵引车","py":"QYC","wb":"DXL","state":"closed","children":[
{"id":"Q11","text":"重型半挂牵引车","py":"ZXBGQYC","wb":"TGURDXL"},
{"id":"Q21","text":"中型半挂牵引车","py":"ZXBGQYC","wb":"KGURDXL"},
{"id":"Q31","text":"轻型半挂牵引车","py":"QXBGQYC","wb":"LGURDXL"}
]
},
{"id":"T","text":"拖拉机","py":"TLJ","wb":"RRS","state":"closed","children":[
{"id":"T11","text":"大型轮式拖拉机","py":"DXLSTLJ","wb":"DGLARRS"},
{"id":"T21","text":"小型轮式拖拉机","py":"XXLSTLJ","wb":"IGLARRS"},
{"id":"T22","text":"手扶拖拉机","py":"SFTLJ","wb":"RRRRS"},
{"id":"T23","text":"手扶变形运输机","py":"SFBXYSJ","wb":"RRYGFLS"}
]
},
{"id":"X","text":"其他","py":"QT","wb":"AW","state":"closed","children":[
{"id":"X99","text":"其他","py":"QT","wb":"AW"}
]
},
{"id":"Z","text":"专项作业车","py":"ZXZYC","wb":"FAWOL","state":"closed","children":[
{"id":"Z11","text":"大型专项作业车","py":"DXZXZYC","wb":"DGFAWOL"},
{"id":"Z21","text":"中型专项作业车","py":"ZXZXZYC","wb":"KGFAWOL"},
{"id":"Z31","text":"小型专项作业车","py":"XXZXZYC","wb":"IGFAWOL"},
{"id":"Z41","text":"微型专项作业车","py":"WXZXZYC","wb":"TGFAWOL"},
{"id":"Z51","text":"重型专项作业车","py":"ZXZXZYC","wb":"TGFAWOL"},
{"id":"Z71","text":"轻型专项作业车","py":"QXZXZYC","wb":"LGFAWOL"}
]
}
]

}]