[
{"id":"01","text":"综合部门（市局中,分局,派出所）","py":"ZHBM（SJZ,FJ,PCS）"},
{"id":"02","text":"法制","py":"FZ"},
{"id":"03","text":"刑侦","py":"XZ"},
{"id":"04","text":"治安","py":"ZA"},
{"id":"05","text":"经侦","py":"JZ"},
{"id":"06","text":"指挥中心","py":"ZHZX"},
{"id":"07","text":"禁毒","py":"JD"},
{"id":"08","text":"出入境","py":"CRJ"},
{"id":"09","text":"责任区","py":"ZRQ"},
{"id":"10","text":"社区","py":"SQ"},
{"id":"11","text":"环保","py":"HB"},
{"id":"12","text":"内保","py":"NB"}
]
