/**
 * Created by christ on 2017/3/27.
 */

[//关系树
    {
        "id": "ROOT", "text": "人员关系代码", "iconCls": "icon-treeroot1", "children": [
        {
            "id": "1", "text": "亲属关系", "py": "QSGJ", "wb": "UNUT", "state": "closed", "children": [
            {"id": "1001", "text": "本人", "py": "BR", "wb": "SW"},
            {"id": "1002", "text": "户主", "py": "HZ", "wb": "YY"},
            {"id": "1010", "text": "配偶", "py": "PO", "wb": "SW"},
            {"id": "1011", "text": "夫", "py": "F", "wb": "F"},
            {"id": "1012", "text": "妻", "py": "Q", "wb": "G"},
            {"id": "1020", "text": "子", "py": "Z", "wb": "B"},
            {"id": "1021", "text": "独生子", "py": "DSZ", "wb": "QTB"},
            {"id": "1022", "text": "长子", "py": "ZZ", "wb": "TB"},
            {"id": "1023", "text": "次子", "py": "CZ", "wb": "UB"},
            {"id": "1024", "text": "三子", "py": "SZ", "wb": "DB"},
            {"id": "1025", "text": "四子", "py": "SZ", "wb": "LB"},
            {"id": "1026", "text": "五子", "py": "WZ", "wb": "GB"},
            {"id": "1027", "text": "养子和继子", "py": "YZHJZ", "wb": "UBTXB"},
            {"id": "1028", "text": "女婿", "py": "NX", "wb": "VV"},
            {"id": "1029", "text": "其他儿子", "py": "QTEZ", "wb": "AWQB"},
            {"id": "1030", "text": "女", "py": "N", "wb": "V"},
            {"id": "1031", "text": "独生女", "py": "DSN", "wb": "QTV"},
            {"id": "1032", "text": "长女", "py": "ZN", "wb": "TV"},
            {"id": "1033", "text": "次女", "py": "CN", "wb": "UV"},
            {"id": "1034", "text": "三女", "py": "SN", "wb": "DV"},
            {"id": "1035", "text": "四女", "py": "SN", "wb": "LV"},
            {"id": "1036", "text": "五女", "py": "WN", "wb": "GV"},
            {"id": "1037", "text": "养女或继女", "py": "YNHJN", "wb": "UVAXV"},
            {"id": "1038", "text": "儿媳", "py": "EX", "wb": "QV"},
            {"id": "1039", "text": "其他女儿", "py": "QTNE", "wb": "AWVQ"},
            {"id": "1040", "text": "孙子、孙女或外孙子、外孙女", "py": "SZ、SNHWSZ、WSN", "wb": "BB、BVAQBB、QBV"},
            {"id": "1041", "text": "孙子", "py": "SZ", "wb": "BB"},
            {"id": "1042", "text": "孙女", "py": "SN", "wb": "BV"},
            {"id": "1043", "text": "外孙子", "py": "WSZ", "wb": "QBB"},
            {"id": "1044", "text": "外孙女", "py": "WSN", "wb": "QBV"},
            {"id": "1045", "text": "孙媳妇或外孙媳妇", "py": "SXFHWSXF", "wb": "BVVAQBVV"},
            {"id": "1046", "text": "孙女婿或外孙女婿", "py": "SNXHWSNX", "wb": "BVVAQBVV"},
            {"id": "1047", "text": "曾孙子或外曾孙子", "py": "CSZHWCSZ", "wb": "UBBAQUBB"},
            {"id": "1048", "text": "曾孙女或外曾孙女", "py": "CSNHWCSN", "wb": "UBVAQUBV"},
            {"id": "1049", "text": "其他孙子、孙女或外孙子外孙女", "py": "QTSZ、SNHWSZWSN", "wb": "AWBB、BVAQBBQBV"},
            {"id": "1050", "text": "父母", "py": "FM", "wb": "WX"},
            {"id": "1051", "text": "父亲", "py": "FQ", "wb": "WU"},
            {"id": "1052", "text": "母亲", "py": "MQ", "wb": "XU"},
            {"id": "1053", "text": "公公", "py": "GG", "wb": "WW"},
            {"id": "1054", "text": "婆婆", "py": "PP", "wb": "II"},
            {"id": "1055", "text": "岳父", "py": "YF", "wb": "RW"},
            {"id": "1056", "text": "岳母", "py": "YM", "wb": "RX"},
            {"id": "1057", "text": "继父或养父", "py": "JFHYF", "wb": "XWAUW"},
            {"id": "1058", "text": "继母或养母", "py": "JMHYM", "wb": "XXAUX"},
            {"id": "1059", "text": "其他父母关系", "py": "QTFMGJ", "wb": "AWWXUT"},
            {"id": "1060", "text": "祖父母或外母父母", "py": "ZFMHWMFM", "wb": "PWXAQXWX"},
            {"id": "1061", "text": "祖父", "py": "ZF", "wb": "PW"},
            {"id": "1062", "text": "祖母", "py": "ZM", "wb": "PX"},
            {"id": "1063", "text": "外祖父", "py": "WZF", "wb": "QPW"},
            {"id": "1064", "text": "外祖母", "py": "WZM", "wb": "QPX"},
            {"id": "1065", "text": "配偶的曾祖父或曾祖母", "py": "PODCZFHCZM", "wb": "SWRUPWAUPX"},
            {"id": "1066", "text": "曾祖父", "py": "CZF", "wb": "UPW"},
            {"id": "1067", "text": "曾祖母", "py": "CZM", "wb": "UPX"},
            {"id": "1068", "text": "配偶的曾祖父母或外曾祖父母", "py": "PODCZFMHWCZFM", "wb": "SWRUPWXAQUPWX"},
            {"id": "1069", "text": "其他祖父母或外祖父母", "py": "QTZFMHWZFM", "wb": "AWPWXAQPWX"},
            {"id": "1070", "text": "兄弟姐妹", "py": "XDJM", "wb": "KUVV"},
            {"id": "1071", "text": "兄", "py": "X", "wb": "K"},
            {"id": "1072", "text": "嫂", "py": "S", "wb": "V"},
            {"id": "1073", "text": "弟", "py": "D", "wb": "U"},
            {"id": "1074", "text": "弟媳", "py": "DX", "wb": "UV"},
            {"id": "1075", "text": "姐姐", "py": "JJ", "wb": "VV"},
            {"id": "1076", "text": "姐夫", "py": "JF", "wb": "VF"},
            {"id": "1077", "text": "妹妹", "py": "MM", "wb": "VV"},
            {"id": "1078", "text": "妹夫", "py": "MF", "wb": "VF"},
            {"id": "1079", "text": "其他兄弟姐妹", "py": "QTXDJM", "wb": "AWKUVV"},
            {"id": "1080", "text": "其他", "py": "QT", "wb": "AW"},
            {"id": "1081", "text": "伯父", "py": "BF", "wb": "WW"},
            {"id": "1082", "text": "伯母", "py": "BM", "wb": "WX"},
            {"id": "1083", "text": "叔父", "py": "SF", "wb": "HW"},
            {"id": "1084", "text": "婶母", "py": "SM", "wb": "VX"},
            {"id": "1085", "text": "舅父", "py": "JF", "wb": "VW"},
            {"id": "1086", "text": "舅母", "py": "JM", "wb": "VX"},
            {"id": "1087", "text": "姨夫", "py": "YF", "wb": "VF"},
            {"id": "1088", "text": "姨母", "py": "YM", "wb": "VX"},
            {"id": "1089", "text": "姑父", "py": "GF", "wb": "VW"},
            {"id": "1090", "text": "姑母", "py": "GM", "wb": "VX"},
            {"id": "1091", "text": "堂兄弟、堂姐妹", "py": "TXD、TJM", "wb": "IKU、IVV"},
            {"id": "1092", "text": "表兄弟、表姐妹", "py": "BXD、BJM", "wb": "GKU、GVV"},
            {"id": "1093", "text": "侄子", "py": "ZZ", "wb": "WB"},
            {"id": "1094", "text": "侄女", "py": "ZN", "wb": "WV"},
            {"id": "1095", "text": "外甥", "py": "WS", "wb": "QT"},
            {"id": "1096", "text": "外甥女", "py": "WSN", "wb": "QTV"},
            {"id": "1097", "text": "其他亲属", "py": "QTQS", "wb": "AWUN"}
        ]
        },
        {
            "id": "2", "text": "非亲属关系", "py": "FQSGJ", "wb": "DUNUT", "state": "closed", "children": [
            {"id": "2010", "text": "同案人", "py": "TAR", "wb": "MPW"},
            {"id": "2020", "text": "朋友", "py": "PY", "wb": "ED"},
            {"id": "2021", "text": "同伙", "py": "TH", "wb": "MW"},
            {"id": "2022", "text": "同监", "py": "TJ", "wb": "MJ"},
            {"id": "2023", "text": "结拜兄弟(姐妹)", "py": "JBXD(JM)", "wb": "XRKU(VV)"},
            {"id": "2024", "text": "赌友", "py": "DY", "wb": "MD"},
            {"id": "2030", "text": "同事", "py": "TS", "wb": "MG"},
            {"id": "2031", "text": "同乡", "py": "TX", "wb": "MX"},
            {"id": "2032", "text": "同学", "py": "TX", "wb": "MI"},
            {"id": "2033", "text": "校友", "py": "XY", "wb": "SD"},
            {"id": "2034", "text": "战友", "py": "ZY", "wb": "HD"},
            {"id": "2035", "text": "学友", "py": "XY", "wb": "ID"},
            {"id": "2036", "text": "网友", "py": "WY", "wb": "MD"},
            {"id": "2040", "text": "师生", "py": "SS", "wb": "JT"},
            {"id": "2041", "text": "师徒", "py": "ST", "wb": "JT"},
            {"id": "2042", "text": "教友", "py": "JY", "wb": "FD"},
            {"id": "2050", "text": "邻居", "py": "LJ", "wb": "WN"},
            {"id": "2060", "text": "主雇", "py": "ZG", "wb": "YY"},
            {"id": "2061", "text": "合伙人", "py": "HHR", "wb": "WWW"},
            {"id": "2062", "text": "客户", "py": "KH", "wb": "PY"},
            {"id": "2070", "text": "恋人", "py": "LR", "wb": "YW"},
            {"id": "2071", "text": "情人", "py": "QR", "wb": "NW"},
            {"id": "2072", "text": "同性恋", "py": "TXL", "wb": "MNY"},
            {"id": "2080", "text": "前夫妻", "py": "QFQ", "wb": "UFG"},
            {"id": "2081", "text": "前夫", "py": "QF", "wb": "UF"},
            {"id": "2082", "text": "前妻", "py": "QQ", "wb": "UG"},
            {"id": "2090", "text": "其他非亲属", "py": "QTFQS", "wb": "AWDUN"}
        ]
        }
    ]

    }
    ]